### ISSUE TITLE
When song is scrobbled on Last.fm

### ISSUE THREAD

**Issue by diggitydogg** [radiant-player/radiant-player-mac#126]
It would be good to have finer tuning of when a song is scrobbled. Having it scrobbled immediately doesn't allow me to skip the bad songs without them being scrobbled. 

This screenshot (http://www.dropbox.com/s/1k29guffy7ow0zt/Screenshot%202014-04-08%2010.34.18.png) is from a Chrome extension called Prime Player for Google Music (http://github.com/svenrecknagel/Prime-Player-Google-Play-Music) and has some great ideas for when it should happen.

**Comment by chrismou** [comment]
Feature added in #428
