### ISSUE TITLE
Add HTML5 Support

### ISSUE THREAD

**Issue by zlassiter** [radiant-player/radiant-player-mac#149]
Please add HTML5 support so I don't have to download Flash.  
![screen shot 2014-05-01 at 12 28 53 pm](https://cloud.githubusercontent.com/assets/2416534/2854177/bf84155c-d14d-11e3-9161-544e6f2e5065.png)

**Comment by smudge** [comment]
HTML5 support seems broken for me. It's an issue on Google's end (because it's not working in Firefox either), but I was wondering if anyone else has found any solutions, other than installing flash (which I don't really want to do just for the sake of listening to music).
