### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by bkensey** [radiant-player/radiant-player-mac#17]
This one may be a bit of a stretch outside of Chrome, but it would be a great feature to bring it into full parity with the web app.

**Comment by ckcollab** [comment]
Bumping this, would be really cool to do this! Almost a year since this was last updated, apologies if it's still not feasible.

**Comment by tuckbick** [comment]
It might useful to look into how Popcorn Time integrated their support for Chromecast:
https://git.popcorntime.io/groups/popcorntime
