### ISSUE TITLE
Provide 2x assets

### ISSUE THREAD

**Issue by kbhomes** [radiant-player/radiant-player-mac#173]
Some of the assets are too low quality for Retina screens.

**Comment by chrismou** [comment]
Which assets in particular @kbhomes ? I may be able to blow some of the images up on Illustrator and export them in at a crazy high resolution for you to use

**Comment by jacobwgillespie** [comment]
@chrismou I'm guessing they're in here: https://github.com/radiant-player/radiant-player-mac/tree/master/radiant-player-mac/images.  We should go through and figure out what we're actually using here and what needs to be retina.

**Comment by chrismou** [comment]
Cool. Not sure exactly what @kbhomes had in mind - I'm on a retina macbook and it all looks fine to me, so perhaps I'm looking in the wrong place.

**Comment by jacobwgillespie** [comment]
Website images!  That's something we can retina-ize...

**Comment by jadengore** [comment]
@jacobwgillespie @chrismou Are images still an issue?

**Comment by jacobwgillespie** [comment]
Potentially yeah - you can check the website - a lot of the images are blurry on retina screens.  I don't think any resources in the app need updating.

**Comment by jacobwgillespie** [comment]
This has likely been resolved.
