### ISSUE TITLE
Reduce width of window border chrome elements

### ISSUE THREAD

**Issue by phaseOne** [radiant-player/radiant-player-mac#182]
To create more blend with the OS, the borders (mostly the top) should be reduced in width. Also, the **search icon should be moved to the left**. *expand the images for better scale.*

For example Spotify:
![](http://new.tinygrab.com/9c646d25b27e78c7e12dcad67d7beb105f49c1f470.png)

Everything is far more condensed. Perhaps even pushing up into close button & fullscreen territory might be an option.

Finder:
![](http://new.tinygrab.com/9c646d25b209a52ca46494a240865fe8db44c53c1d.png)

Current Radiant GUI:
![](http://new.tinygrab.com/9c646d25b28c0779321ab845d9053be8fd104360db.png)

Now tell me that that doesn't look clunky and chunky in comparison. Totally not bashing on your work, it's great; but this is the beauty of open source, quality colla<b>bro</b>ation.

**Comment by jacobwgillespie** [comment]
Closing this - the UI here is from an outdated version of the app.
