### ISSUE TITLE
Window breakpoints and minimum width

### ISSUE THREAD

**Issue by phaseOne** [radiant-player/radiant-player-mac#183]
Most Mac apps have breakpoints that **collapse down** the UI and eventually set a **minimum width** to the window. Just a nice polish ([![flag of Poland](http://new.tinygrab.com/9c646d25b2f6307e767ca74ad4f14969153fb95975.png)](https://en.wikipedia.org/wiki/Poland)) feature. *(bet you can't read the word polish without thinking of Poland for the next 15 minutes)*

![screen shot 2014-06-05 at 9 10 55 pm](https://cloud.githubusercontent.com/assets/1310985/3195660/8c4845f6-ed17-11e3-91ce-452f0122e421.png)
*hides search bar*

![screen shot 2014-06-05 at 9 01 06 pm](https://cloud.githubusercontent.com/assets/1310985/3195661/92b41b86-ed17-11e3-8426-87b175a14f0c.png)

**Comment by jacobwgillespie** [comment]
This applies to an older version of the UI (I think, the one with the search bar) - I'm closing, though feel free to ping if you're looking for something different.
