### ISSUE TITLE
"Added songs" panel does not respect theme choice

### ISSUE THREAD

**Issue by AngelEzquerra** [radiant-player/radiant-player-mac#184]
When using the "Spotify black" theme the "Added x songs" panel that is shown while new songs are being uploaded to google music does not follow the theme color scheme (it is white, rather than black) as can be seen on the following screenshot:

![screen shot 2014-06-08 at 1 13 30](https://cloud.githubusercontent.com/assets/6682868/3210018/8207843e-ee99-11e3-9fc0-680bc49aa410.png)

**Comment by jacobwgillespie** [comment]
Closing as this theme is outdated.
