### ISSUE TITLE
Media buttons stop working after a day or so

### ISSUE THREAD

**Issue by jrajav** [radiant-player/radiant-player-mac#202]
They've stopped working after a day or so without fail for about a week now. OS X 10.9.3, Radiant 1.2.1, Flash 13.0.0.214, not using the alternative method. I'm not using other apps that might take them over, except perhaps MplayerX, though prior to 1.2.1 I'm pretty sure I was using them in harmony.

I can do whatever you want to investigate, but not sure what that would be.

**Comment by jacobwgillespie** [comment]
This has been resolved
