### ISSUE TITLE
Pausing and sleep will kill the audio until next track

### ISSUE THREAD

**Issue by LeGourmand** [radiant-player/radiant-player-mac#206]
Only on Yosemite

If you pause a track and then lock/go to sleep when you resume and try to un-pause, the track will continu playing but there will be no sound, until the next track.

EDIT: It's now also happening when only pausing and resuming a song, but when i tried earlier it was fine.

**Comment by jacobwgillespie** [comment]
@LeGourmand I'm closing this as it's been a while and I can't replicate, but feel free to ping if it's still happening.
