### ISSUE TITLE
Does not respond with 'Loading Music Library...'

### ISSUE THREAD

**Issue by yasuoza** [radiant-player/radiant-player-mac#211]
Application stops with 'Loading Music Library...'.

![screen shot 2014-07-15 at 14 23 09](https://cloud.githubusercontent.com/assets/736506/3580879/3e05e5f0-0be0-11e4-9898-e23329b3fec4.png)

However in Chrome I can open and listen Google Music.

radiant-player-mac worked well so far, but it does not start today.

OSX 10.9.4
Adobe flash is up to date

**Comment by GitPrudence** [comment]
The "uBlock Origins" extension was causing my issue. Once I set the URL in the whitelist, The website loaded as expected.
