### ISSUE TITLE
Using media keys to go previous/next song will skip one song

### ISSUE THREAD

**Issue by ctbear** [radiant-player/radiant-player-mac#223]
I am on 1.2.1 and this has been happening ever since media keys were supported.
Pressing the media key to go to previous or next song will always skip one. Example:

Song 1 <-- currently playing
Song 2
Song 3
Song 4

<Press the next song key once>

Song 1
Song 2
Song 3 <-- now playing
Song 4

This happens when I use the media key on my Macbook Pro Retina and when I use a custom keyboard shortcut set by BetterTouchTool.
I have tried to disable BetterTouchTool and it still does the same thing.
The Play/Pause button works fine.

**Comment by jacobwgillespie** [comment]
This has been resolved.
