### ISSUE TITLE
iTunes style notifications don't work on Yosemite

### ISSUE THREAD

**Issue by pixeldennisity** [radiant-player/radiant-player-mac#231]
Hello, Just found out about radiant player. Super excited to use the beautiful ui but as soon as I fire it up I get error. Radiant seems to have automatically logged me into google but I have no access to my library.

Running latest Yosemite ... looking forward to trying radiant out.

**Comment by jacobwgillespie** [comment]
Since this is old, I'm closing.  Feel free to post back if you're still experiencing issues.
