### ISSUE TITLE
Radiant Player Hangup on Yosemite 

### ISSUE THREAD

**Issue by b3autykill3r** [radiant-player/radiant-player-mac#235]
Whenever I am streaming music for an extended period of time, the player will hang and must force quit to exit. Here is the console print out of what happened. 
Also, on restart from the force quit the GUI on the bottom bar (i.e. Play, FF, RW, VOL speakers) are non existent. Also attached is a screenshot of that on opening. 
![screen shot 2014-10-02 at 9 14 13 am 2](https://cloud.githubusercontent.com/assets/8284767/4491194/0a8afa00-4a36-11e4-9a21-e9a41dfecfae.png)

![screen shot 2014-10-02 at 9 08 26 am](https://cloud.githubusercontent.com/assets/8284767/4491173/da6c12a0-4a35-11e4-95fb-05ff20ee2eb5.png)

**Comment by chrismou** [comment]
Can anyone can confirm if they're still seeing this issue?  Feel free to test using this build https://github.com/chrismou/radiant-player-mac/releases/tag/v1.5.0-cyan (up to date with master as of this morning)

@b3autykill3r @aaronortiz @smackjack3

**Comment by jadengore** [comment]
Ping to everyone in this conversation, any issues still?
