### ISSUE TITLE
Always sort "Songs" by Artist, Album, etc.

### ISSUE THREAD

**Issue by AlecRobertson** [radiant-player/radiant-player-mac#241]
Currently, in the Songs tab of My Library, the way songs are ordered can be selected, be that by Artist, Album, etc.

However, when the tab is changed to Artists, Albums, or, when the view is changed to anything else other than, My Library, the way the songs are ordered is reset to order by name.

Is it possible to always sort songs by Artist, Album, etc?

**Comment by jacobwgillespie** [comment]
Unfortunately it looks like this is something on Google's end of things - if you check out the help and feedback option in the GPM menu, you could always send it as a suggestion to Google.
