### ISSUE TITLE
Back/Forward buttons appear clickable even when there is no action

### ISSUE THREAD

**Issue by psthompson** [radiant-player/radiant-player-mac#244]
Right after opening Radiant Player, the back/forward button appear clickable and can be clicked even though there is no back/forward action for the button.

![radiant player](https://cloud.githubusercontent.com/assets/2582474/4666216/861897a6-5551-11e4-857c-1af2fbce715b.png)

When there is no back/forward action, the buttons should be greyed out and not clickable.

![finder - no action](https://cloud.githubusercontent.com/assets/2582474/4666331/6eb6f624-5552-11e4-8d7b-8365c531ccfa.png)

**Comment by jacobwgillespie** [comment]
This refers to an older UI - closing
