### ISSUE TITLE
Noticed poor sound since upgrade to 1.3.1

### ISSUE THREAD

**Issue by vdite** [radiant-player/radiant-player-mac#247]
I have noticed poor sound (on Headphones) since upgrade to 1.3.1. Chrome working fine.
Latest Mavericks.

**Comment by ploum** [comment]
I think I've noticed the same issue. I cannot be 100% certain because sound quality is something very hard to quantify.

**Comment by kbhomes** [comment]
Could it be that the performance issues in 1.3.1 were causing this? I can't think of any reason why sound quality would differ between Chrome and Radiant Player.

**Comment by jacobwgillespie** [comment]
Closing as I cannot replicate, but do ping if this is still happening.
