### ISSUE TITLE
Break out JS integration into separate library

### ISSUE THREAD

**Issue by twolfson** [radiant-player/radiant-player-mac#252]
A while ago, I saw this and started writing my own `node-webkit` wrapper to support all platforms. I used parts of the JS files to get something quick and dirty working.

https://github.com/twolfson/google-music-webkit/blob/1.0.0/lib/google-music.js

In the long term, we should have a common repository that we pull from. Ideally, it would support all modern browsers and be an interface that attaches to the Google Music website:

```js
var googleMusic = new GoogleMusic(window);
```

Let me know if you are interested, otherwise I might fork this repo and strip it down to the JS lib with less singleton assumptions.

**Comment by twolfson** [comment]
As promised, I have began my fork. I finished writing tests for every method (except for experimental features like star ratings). It should be mention that I caught an issue in `Rating.getRating()` which was returning `0` for all thumb ratings.

https://github.com/twolfson/google-music.js

**Comment by twolfson** [comment]
As a heads up, `google-music.js@3.0.0` was updated to support the Material redesign from a few days ago. Let me know if you start using it so we can collaborate on anything that's missing/seems broken =)

**Comment by jacobwgillespie** [comment]
Oh, hey @twolfson - I think this is a great idea - I've started a PR for this at #402

**Comment by jacobwgillespie** [comment]
This has been merged :tada:
