### ISSUE TITLE
Lyrics Support

### ISSUE THREAD

**Issue by zupodaniel** [radiant-player/radiant-player-mac#267]
Any plans to implement some lyrics display support?

**Comment by xjunior** [comment]
Is this still a thing?

**Comment by ohassidi** [comment]
Yup, I would lyrics on my music app

**Comment by stunaz** [comment]
+ 1 for this! it would be Wonderfull to have this feature,

**Comment by kxhitiz** [comment]
:+1:  Would like to have this feature.

**Comment by tonatiuh** [comment]
+1 for this, I would like to have this feature as well.

**Comment by inacionery** [comment]
+1 for this, I would like to have this feature

**Comment by Dreamkeeper** [comment]
+1 for this, I would like to have this feature

**Comment by MarshallOfSound** [comment]
@jacobwgillespie 

This might be of some use
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/lyrics.js

**Comment by BarakaAka1Only** [comment]
I went ahead and made adding Lyrics to Radiant; it's a work in progress nothing fancy, you all can check it out here : https://github.com/radiant-player/radiant-player-mac/issues/536

Let me know what you guys think..
