### ISSUE TITLE
Spotify Black themes no longer dark in playlist view

### ISSUE THREAD

**Issue by brendonrapp** [radiant-player/radiant-player-mac#268]
Not certain exactly when this happened, but I have seen this now on both a 10.9 and 10.10 machine.

![screen shot 2014-11-24 at 8 07 24 pm](https://cloud.githubusercontent.com/assets/170030/5177858/b28a6372-7415-11e4-8eb6-c0482b5ddd97.png)

**Comment by brendonrapp** [comment]
Can we get a new release build soon? This issue makes Radiant almost unusable for me, and this issue has been fixed for over a month.

**Comment by tonybaroneee** [comment]
Follow the work-around here https://github.com/kbhomes/radiant-player-mac/issues/271 (third from last comment) until he cuts a release.
