### ISSUE TITLE
TuneIn radio support

### ISSUE THREAD

**Issue by maticrivo** [radiant-player/radiant-player-mac#276]
Is there anyway to include support for TuneIn radio like there is for last.fm?

**Comment by jacobwgillespie** [comment]
Does this mean listening to TuneIn stations or scrobbling to TuneIn?

**Comment by chrismou** [comment]
I'm closing this ticket as being beyond the scope of Radiant Player. Or at least this version.

Perhaps extending out beyond Google Music is something we could look at in the Electron version, but for now I'd like to say shelve the idea and focus on improvements.
