### ISSUE TITLE
Dragging and droping image displays it in the browser pane

### ISSUE THREAD

**Issue by rameshdharan** [radiant-player/radiant-player-mac#284]
I was editing Album Info and trying to set artwork. Out of curiosity I tried dragging an image onto the Radiant Player Window to see if I could drop it on to the Album Artwork element. Instead this simply replaced the entire Radiant Player content area with the image. I had to use the Cmd-Left keyboard shortcut to get back to the music page (and wait for the site to reload). 

Presumably an easy fix here is to simply disable the window as a drop target.

**Comment by jacobwgillespie** [comment]
Looks like this was fixed by #307.
