### ISSUE TITLE
Last FM Scrobbling Support Broken

### ISSUE THREAD

**Issue by FatalEnigma** [radiant-player/radiant-player-mac#285]
I've noticed that the player has a habit of not scrobbling tracks to my last fm profile. If I listen to a playlist of songs continuously and check my profile, some or possibly all the tracks are not there. If I enable the last fm button, when I first start playing the track it is shown as currently playing, but if I check back near the end, the song has vanished and it only shows the previous scrobbles.

**Comment by tjanson** [comment]
Just noticed the same thing, except no tracks were being scrobbled at all. I then went to the Preferences and “deauthorized” the login, entered my login data again and clicked “authorize”, result:

> Unable to login to Last.fm.

**Comment by code-for-coffee** [comment]
I am unable to scrobble songs. I have de-authorized and re-authorized my account successfully. The Last.fm "Recent Scrobbles" feature works and fetches a list of songs successfully. I can even "Love" a track and that feature works correctly. 

I am unfamiliar with OS X development; is there an easy way to attach a debugger to a live process using XCode? Similar to what you can do with Visual Studio? More than happy to dig into it further.

**Comment by chrismou** [comment]
Fixed in https://github.com/radiant-player/radiant-player-mac/pull/378
