### ISSUE TITLE
Sound enhancements not working because Safari's sandboxing Flash Player?

### ISSUE THREAD

**Issue by a8vam** [radiant-player/radiant-player-mac#290]
Something I noticed:

I'm using Hear app for improving the sound quality on Yosemite. It seems it's not working with Radiant Player due to Safari sandboxing Flash Player. Now I tried to allow Flash websites to run in Unsafe mode without sandboxing in Safari's Preferences but it doesn't seem to effect Radiant Player. Any ideas how to make it work?

**Comment by kbhomes** [comment]
Does the Hear.app work in Safari if Flash is run sandboxed? I'm asking because I have no experience with Hear.app and don't know how to approach it.

**Comment by a8vam** [comment]
It doesn't work.

**Comment by jacobwgillespie** [comment]
Going to close this for now - feel free to ping if you get this working with Safari.
