### ISSUE TITLE
Increase transparency of sidebar?

### ISSUE THREAD

**Issue by FezVrasta** [radiant-player/radiant-player-mac#298]
Can I increase the transparency of the sidebar and of other parts editing the theme or is something hard coded?

If is hard coded, could be changed to be able to change the opacity using some CSS rule?

Thanks.

**Comment by FezVrasta** [comment]
For what I've understood so far, the entire body of the app is transparent, and then you set a white background in the parts that don't need to be translucent.

The only part where I see an opacity rule like that is here:
https://github.com/kbhomes/radiant-player-mac/blob/7806af2d446e8f3799e1c9e89ec1300d3437956a/radiant-player-mac/Support/VisualEffectView.m#L16

I think would be great make it tweakable directly by CSS or at least from the options of the theme or something like this...

Thanks!

**Comment by jacobwgillespie** [comment]
So, from what I can tell, the app is currently totally opaque, so I'm not sure if we still need this issue (since it doesn't look like we're doing transparency anymore).  I'm going to close this as part of issue cleanup, but feel free to ping if you'd like this to be re-investigated.
