### ISSUE TITLE
Useful keyboard shortcuts

### ISSUE THREAD

**Issue by kbhomes** [radiant-player/radiant-player-mac#3]
Some keyboard shortcuts when viewing the main application would be useful:

Volume:
- [x] `⌥↑` to increase player volume
- [x] `⌥↓` to decrease player volume

Rating:
- [x] `⌘J` to toggle thumbs up
- [x] `⌘K` to toggle thumbs down

Other:
- [x] `⌘S` to toggle shuffle
- [x] `⌘R` to change repeat mode
- [x] `⌘T` to toggle visualization

**Comment by EliasVansteenkiste** [comment]
It would be nice to be able to toggle thumbs up while the radiant player resides in the background.
In the same way as the apple play/pause, next and previous buttons work.
