### ISSUE TITLE
Mini player becomes unresponsive

### ISSUE THREAD

**Issue by szechyjs** [radiant-player/radiant-player-mac#302]
Once you hover over the stars they seem to take the foreground and then make the whole miniplayer unresponsive until radiant is closed and reopened.

None of the buttons in the mini player work when its in this state. The progress bar and track information will update though.

![screen shot 2015-04-08 at 2 31 35 pm](https://cloud.githubusercontent.com/assets/847739/7052371/302b47c4-ddfc-11e4-92d7-d5313607644d.png)

Version: 1.3.3

**Comment by shawn-mitch** [comment]
I have the same issue, except the controls are still responsive for me. It seems that there's no code being called to hide the rating bar after it's been activated.

**Comment by chrismou** [comment]
Google look to have removed the 5 star ratings option, and I can't seem to replicate this with the thumb up/down system  https://productforums.google.com/forum/#!topic/play/HwKmVF5N5YA
