### ISSUE TITLE
Media Keys Stop Working

### ISSUE THREAD

**Issue by krisdestruction** [radiant-player/radiant-player-mac#310]
Media keys stop working after another application takes over. Radiant player doesn't appear to be as integrated with media keys compared to iTunes. I believe there is a limitation where the latest application takes control, but perhaps Radiant Player could employ some method to aggressive take control of the keys like Vox.

Note that this seems to have a conflicting report with the issue #279 . That one says that Radiant Player is too aggressive, but this one is about it not being aggressive enough.

To reproduce:
1. Open Radiant Player
2. Start playing a track
3. Press Pause/Play media button
4. Open a new tab in Safari and navigate to google.ca
3. Press Pause/Play media button (doesn't work)

**Comment by jeffubelhor** [comment]
I would just like to point out, as the creator of #279 , that I have seen both of these issues exist at separate times.

**Comment by krisdestruction** [comment]
To clarify, you mean that sometimes it overtakes and sometimes it gets overtaken?

**Comment by jeffubelhor** [comment]
Yes, I've seen instances of both happening.

**Comment by krisdestruction** [comment]
That's quite strange, I wonder if OS X has some sort of priority set. If so, then Radiant player could allow the user to specify the priority?

**Comment by UnicornDelight** [comment]
I've noticed that if boot your computer and open iTunes (or any app that uses the media keys) first they will stay bound to that app instead.

I imagine a fix would be to override that, but I've always had stupid issues overriding media keys in my past experiences.

Another fix would be to directly assign them via the OS preferences panel.

**Comment by jacobwgillespie** [comment]
I'm going to close this one for now as the original issue appears to be fixed.  Feel free to ping back or create a new issue if anything crops up again.

**Comment by krisdestruction** [comment]
Looks fixed, thanks!
