### ISSUE TITLE
Last.fm gone?

### ISSUE THREAD

**Issue by sleeptdebt** [radiant-player/radiant-player-mac#314]
Is Last.fm integration gone? Can't find the settings anymore, nor any mention of it being removed, etc.

**Comment by bondt** [comment]
@sleeptdebt, hit Cmd+, (Command + comma) to enter Radiant Player's settings. What's the fifth item you see there?

**Comment by bondt** [comment]
Hm, but scrobbling seems to be broken...

**Comment by sleeptdebt** [comment]
Ah, I've been looking in Settings - not Prefs. Found it now, thanks!
