### ISSUE TITLE
keyboard controls trigger but fail when Radiant Player is minimized

### ISSUE THREAD

**Issue by cdelorme** [radiant-player/radiant-player-mac#327]
Keyboard hotkeys such as space and left/right arrows to pause or switch to next and previous tracks no longer work when the window is minimized, but the menu indicates the controls are being captured.

While I would prefer that it be controllable while minimized, if removing controls while the window is minimized was intended then the menu should probably not indicate when it captures these keypresses.

**Comment by jacobwgillespie** [comment]
Controls properly work when minimized now - closing
