### ISSUE TITLE
Selecting text in search bar drags window

### ISSUE THREAD

**Issue by schizzle** [radiant-player/radiant-player-mac#337]
OSX 10.10.2

Trying to select text in the search bar with the cursor drags the window instead. This is when the app is not in fullscreen mode.

**Comment by jacobwgillespie** [comment]
This has been resolved.

**Comment by schizzle** [comment]
I'm still having this issue on 1.6.2.

**Comment by jacobwgillespie** [comment]
I can't reproduce - are you using a particular theme?

**Comment by schizzle** [comment]
It's the default theme. Do you want any specific info about my setup/environment? For the most part I haven't touched the settings.

**Comment by jacobwgillespie** [comment]
Check out #454 - looks like we'll likely have a preference to disable the custom title bar (which has been fixing performance issues for people)
