### ISSUE TITLE
Song stopping early?

### ISSUE THREAD

**Issue by ckcollab** [radiant-player/radiant-player-mac#339]
When listening to an instant mix the songs seem to be stopping at least ~10s early? Using 1.4.0 in Mac Mavericks

**Comment by ivancamilov** [comment]
Same thing begun to happen to me a few days ago.

**Comment by kbhomes** [comment]
Are these problems also existent in Safari?

**Comment by jacobwgillespie** [comment]
I'm unable to reproduce, so closing for now - feel free to ping if you're still experiencing.

**Comment by ckcollab** [comment]
Will do, thanks for the hard work!
