### ISSUE TITLE
Albums not showing all tracks

### ISSUE THREAD

**Issue by arondraper** [radiant-player/radiant-player-mac#354]
Since yesterday all my albums on Google music when using Radiant Player 1.4.0 are missing tracks.  Some albums are missing one or two tracks but most are now only showing a few of the tracks form that album.

If I load up the same album via my web browser (chrome in this example) then all the tracks are displayed.  

I tried deleting Radiant player and re-downloaded, reinstalled and logged back into my account but still the same only a handful of tracks show for each album.

The screenshots attached are one of radiant player and one of the same album via my browser.

![screen shot 2015-08-28 at 15 00 03](https://cloud.githubusercontent.com/assets/4047428/9548009/d553ad5a-4d95-11e5-950c-51f6eeae0d85.png)
![screen shot 2015-08-28 at 14 59 19](https://cloud.githubusercontent.com/assets/4047428/9548010/d5550484-4d95-11e5-9e60-a39a921525f6.png)

**Comment by rwoodpecker** [comment]
+1

**Comment by shawn-mitch** [comment]
+1 I've had this happen to me as well. It seems like it's semi-random, as it's usually the same albums that are missing songs, but the songs missing change.

**Comment by jacobwgillespie** [comment]
I'm closing this as it's likely an issue on Google's end.  Feel free to post back if you run into any issues.
