### ISSUE TITLE
Last.fm integration not working on El Capitan

### ISSUE THREAD

**Issue by ameraljovic** [radiant-player/radiant-player-mac#368]
When trying to authorize my Last.fm account I just get a message: Unable to login to Last.fm.
I use version v1.4.1.

**Comment by ameraljovic** [comment]
It seems that this is a issue only on the newest version. With v.1.4.0 it works.

**Comment by nivong** [comment]
Same here

**Comment by chrismou** [comment]
(Y) Same

@ameraljovic Which 1.4.0 version are you using?  The official binary has the issue with the white box in the bottom left and all the songs skipping.

**Comment by ameraljovic** [comment]
@chrismou Yes, the official binary v1.4.0.

**Comment by patrickhpan** [comment]
+1 for broken on 1.4.1, El Capitan.

**Comment by nivong** [comment]
Still broken on 1.4.1 and the 1.4.0 patched

**Comment by chrismou** [comment]
Yeah, I can't get it working on any version. 1.4.0 official I get the white box of death, 1.4.0 temp and 1.4.1 the music plays but it won't scrobble. I've reverted back to the web player for now.

I may have a go at getting it running in Xcode and see if I can see the problem, but Mac development isn't really my speciality so I'm not holding out too much hope. I did wonder if it had something to do with the last.fm redesign/borked API, but it seems strange it would work right up until upgrading to El Capitan.

**Comment by chrismou** [comment]
Right, I seem to have fixed it locally. It seems to be something to do with El Capitan forcing connections that are using HTTPS to be TLS 1.2. I'm not sure why that affects scrobbling, but disabling App Transport Security seems to have fixed it for me. Not sure if that's a dirty workaround or not, but I'll put in a pull request to @kbhomes and see what he thinks.

In the meantime, I've released my fixed version here: https://github.com/chrismou/radiant-player-mac/releases/tag/v1.4.1

Would appreciate any testing/feedback on whether it works for you. @ameraljovic @nivong @patrickhpan

**Comment by chrismou** [comment]
Only thing I couldn't work out was how to change the version number, so it's trying to get me to "upgrade" to 1.4.1. Small price to pay I guess.

**Comment by nivong** [comment]
Thanks for the fix @chrismou it works!

**Comment by vegbrasil** [comment]
Thanks a lot @chrismou.

**Comment by chrismou** [comment]
Cheers guys. I've put in a pull request here: https://github.com/kbhomes/radiant-player-mac/pull/378

**Comment by ameraljovic** [comment]
@chrismou, works like a charms! :beers:

**Comment by vegbrasil** [comment]
Is the hotkeys not working on @chrismou's version? Or just here?

**Comment by chrismou** [comment]
No, apparently not.  Doesn't seem to be working on @kbhomes's master branch either.

**Comment by motokochan** [comment]
The media keys are likely something with the 10.11.1 update, issue #381 is tracking that.

**Comment by chrismou** [comment]
Fixed in https://github.com/kbhomes/radiant-player-mac/pull/378 - should be available in the next release (or by building your own binary from master, if you're feeling impatient) :-)

**Comment by chrismou** [comment]
Hmm, still not working on master. Looks unrelated to the original issue. Reopening the ticket while I look into wtf has happened

**Comment by chrismou** [comment]
Now fixed in https://github.com/radiant-player/radiant-player-mac/pull/400
