### ISSUE TITLE
Queue messed up on latest release

### ISSUE THREAD

**Issue by FezVrasta** [radiant-player/radiant-player-mac#369]
![image](https://cloud.githubusercontent.com/assets/5382443/10337201/7fe3a658-6cfe-11e5-8e31-8b85bc03d4ec.png)

We should probably use less specific selectors to avoid such problems on every Play Music update

**Comment by FezVrasta** [comment]
Or better, we may copy the entire CSS of Google Play Music and replace colors with the ones we want. In this way on every update the CSS will be automatically updated.
(we should still support custom CSS to allow to edit other stuff manually)

**Comment by JustinTBrown** [comment]
+1 on this issue. Am experiencing this on both v1.4.1 as well as the v1.4.0 patch done previously by @jacobwgillespie. Both default Google theme and black theme are affected.

**Comment by kbhomes** [comment]
This is fixed with @shawn-mitch's PR at #374.
