### ISSUE TITLE
Clicking on album title in Recent Activity reloads interface

### ISSUE THREAD

**Issue by jrmehle** [radiant-player/radiant-player-mac#370]
This issue was present in 1.4.0 and 1.4.1. Clicking on the name of an album in the Recent Activity section reloads the entire web app inside of the window.

**Comment by brendonrapp** [comment]
+1, this issue has been driving me nuts.

**Comment by kbhomes** [comment]
I confirmed this issue a few days ago but today I am unable to replicate it... I even went back to previous versions to see if a recent commit had inadvertently fixed it, but I was unable to reproduce it. @jrmehle, @brendonrapp, can you two confirm if you're still seeing the issue?

**Comment by jrmehle** [comment]
@kbhomes Checking again with 1.4.1, and I also can no longer produce the issue. It seems maybe Google corrected an issue on their end?

**Comment by kbhomes** [comment]
Seems that way, thanks for the confirmation.
