### ISSUE TITLE
Adding collaborators to project for timely updates

### ISSUE THREAD

**Issue by jadengore** [radiant-player/radiant-player-mac#371]
I started this conversation in #358, but I want it to continue.

As can be seen for the past 2 months, there's been an influx of issues with the infamous "white box" ( #365, #360, #351). Many have had to resort to looking through Github issues for help even though @jacobwgillespie had a quick-fix (#352) PR for the issue for a good while.

@kbhomes Would you be willing to add some collaborators to this project so we can get fixes for Radiant added in a timely manner? I know that you are probably busy with plenty of other things, and I don't expect you to answer every PR within a day, but with an app like Radiant bugs will come up quickly (it is essentially a wrapper for a web app). It would be great if we could deploy binaries more quickly with a dedicated group of project maintainers.

Any thoughts from anyone else on this?

**Comment by jacobwgillespie** [comment]
My thoughts are that first and foremost this is @kbhomes's baby, so I'll defer to whatever he wants.

That being said, I think it would be awesome to move this to an org (maybe @radiant-player? it's available) and add some contributors.  On that front, I'd be happy to help as I can, though I'm not super familiar with Mac development.  I could definitely help with updates related to the HTML / CSS / JS changes.  I even started briefly on a Radiant clone based on Electron in the hopes of a cross-platform / Windows version requested at #316 - maybe alternate projects like that could live under the org umbrella?

Anyways, just an idea - this is an app I use everyday and I'd definitely be happy to help keep it around!

**Comment by benburton** [comment]
I've been using this application 8+ hours a day well before it was renamed Radiant Player from Google Music Player. It's been my primary music player for a very long time.

In the past year or so, I've found myself pulling PR branches and compiling from source to get around issues that have outstanding fixes. I would definitely welcome some other contributors to pick up the slack when @kbhomes doesn't have the bandwidth.

I'm not an Objective-C/Swift/Cocoa developer, so I can't commit to being able to thoroughly code review changes, but I am absolutely willing to give pull requests a logic review, check the changes on the latest OS X, compile the binaries, and distribute them.

**Comment by jadengore** [comment]
@jacobwgillespie @benburton :+1:, thank you for your responses.

I think that if we don't move this to either an organization or open the floor to contributors who want to perform code review/PR merge/timely updates, this project will die.

However, that might not be a bad thing. @jacobwgillespie pointed out that the rise of Electron could bring a Google Play Music player that is truly cross-platform. This might be a project to consider that suceeds Radiant Player, since I believe that the performance issues Radiant currently has will be extremely hard to address not using a more compatible Chromium environment in Electron.

**Comment by shawn-mitch** [comment]
This is just my two cents, but I don't think that this project will live on much longer unless something changes. It seems to me that @kbhomes doesn't have the bandwidth and/or interest in the project that is needed to be the sole contributor on a project that is subject to Google's frequent code changes. 

I see three different possibilities for the future of this project. 1) @kbhomes adds more contributors that are able to keep on top of bug reports and pull requests, also possibly moving the project to an organization. 2) A new project comes along (e.g., Electron) that everyone moves to, and leaves Radiant to die. 3) Someone forks Radiant and add contributors that have been involved on Radiant. Radiant dies.

The only action that will keep Radiant relevant and keep the community around is for @kbhomes to add more contributors. Ignoring this issue will only cause the project to die. No ill will to @kbhomes but I am not holding my breath waiting for this to happen.

**Comment by matheusdias** [comment]
https://github.com/twolfson/google-music-electron

**Comment by matheusdias** [comment]
@jacobwgillespie @benburton @jadengore @shawn-mitch 
https://github.com/twolfson/google-music-electron

**Comment by benburton** [comment]
Thanks for the heads up @matheusdias. Will give it a look next time radiant breaks on me.

**Comment by jadengore** [comment]
@matheusdias This looks cool, but it looks very Linux-focused. Radiant has some great integrations into the notification system of OS X that is useful. Also, I do like the mini-player in the status bar as well.

I'm hoping for a project that pursues Radiant's goals while maintaining its features.

**Comment by jacobwgillespie** [comment]
Yep, thanks @matheusdias - I've looked into that one a bit and agree with @jadengore that it'd be awesome to have a feature-complete clone of Radiant's featureset.

**Comment by matheusdias** [comment]
@jadengore The app works on Windows, Linux and OSX. I tested here on OSX ElCaptain and worked well. The project needs o visual adjusts but it is a alternative way to Radiant.

**Comment by jadengore** [comment]
@matheusdias In my experience, Play/Pause media keys completely didn't work, the element in the status bar was broken/improper resolution, and the app has to be run from the command line. I find it better to just pin a tab in Chrome and use a plugin than using this app.

There are clearly other options, but I want to steer the topic back on track: we are looking to either add project collaborators to review pull requests and maintain this project, or start a separate project that continues the work of @kbhomes.

**Comment by matheusdias** [comment]
@jadengore Ok. I'm a developer (Java, PHP and Ruby) and i am also available to help in this project or on another.

**Comment by jadengore** [comment]
@matheusdias Thanks! :+1:

**Comment by shawn-mitch** [comment]
I agree with @jadengore. Electron would be awesome if I were still rocking Ubuntu. However, Radiant has some baked-in Mac goodness that would need to be added to Electron to put it on the same level for me.

I think we're coming to a crossroads with this project. I doubt we're going to see much input from @kbhomes from here on out. This thread has been sitting here for 2 weeks with no input from him. We had to wait for 3 weeks for him to merge the fix to the app-breaking webcomponents.js bug. There are a few pull requests sitting out there that are fixing some major (albeit, not necessarily app-breaking) UI fixes. If we want Radiant to live on (even in spirit), we're going to have to do it ourselves.

**Comment by jadengore** [comment]
@shawn-mitch Agreed. Here's what I'm leaning towards (since no response from @kbhomes):

1. Open an organization @radiant-player like @jacobwgillespie suggested.
2. Fork kbhomes' work.
3. Add more active project maintainers to address issues.

Any thoughts?

**Comment by benburton** [comment]
@jadengore Can't speak for anyone else, but that was exactly what I was thinking.

**Comment by kbhomes** [comment]
The good news is that it's really great to see how many people like Radiant Player and really want it to continue, and I'm honestly very appreciative of that!

You're all right, I don't quite have the bandwidth at this moment to be a single maintainer and contributor. I think I owe you all an explanation for my absences, which is mostly because of academic commitments stemming from grad school applications, senior-level CS projects, etc.

You guys have the right idea, so I'm going to be creating the organization and transferring this repository to there and adding contributors. I imagine everybody in this thread would be a willing contributor but please let me know otherwise. Again, I'm really sorry for the lack of communication but I'm so glad to see how much you all care.

**Comment by benburton** [comment]
@kbhomes I believe @jadengore has already created it.

**Comment by kbhomes** [comment]
@jadengore Would you be willing to transfer the @radiant-player organization to me?

**Comment by jadengore** [comment]
@kbhomes Yes! I'm going to remove the fork, do you think you can move your repository there as well?

**Comment by kbhomes** [comment]
@jadengore Thank you! I will transfer to the organization as soon as I figure out the correct approach to maintaining the upgrade path. Current versions link to my website and look at this repository for upgrade information and I don't want to break that just yet.

**Comment by motokochan** [comment]
At least for GitHub, references from the old repository will redirect to the new one if you do a transfer via the GH interface/site. If you just fork or push as a new repository, that won't happen. I don't have experience on the website side to know for sure what happens there, although I guess that it would be similar.

**Comment by jadengore** [comment]
@kbhomes I'll make sure the link is maintained, if not I can always provide a PR to your personal website with the updated link if anything breaks (I think your site is open-source?).

**Comment by chrismou** [comment]
Am happy to throw my name into ring to help with maintenance. Always happy to help with useful open source projects where I can.

**Comment by jacobwgillespie** [comment]
@kbhomes, when you have a free moment, can you give the org members write access to the repos here?  I'd love to start triaging some of the backlog of issues, but it looks like we're part of the org but don't yet have access to write to the repos.  Thanks!

**Comment by jadengore** [comment]
@jacobwgillespie Have I added you to radiant-player org? Yeah, we still don't have access until @kbhomes either moves the repo or adds the org as write-access capable.

It might be even smarter to just add anyone in the org with write access, that's how [Bookshelf](https://github.com/tgriesser/bookshelf) maintains write access for its contributors.

**Comment by jacobwgillespie** [comment]
@jadengore - yep, thanks for the help!  We've been added, but it'll take @kbhomes to enable write access now that ownership has transferred.

**Comment by kbhomes** [comment]
Sorry guys, I didn't realize you needed to add organization members to the repository explicitly. I moved the repository to the org a few days ago since I determined that nothing would break in the transition but I'd forgotten about that, sorry!

**Comment by kbhomes** [comment]
Thanks @chrismou, I'll add you to the team!

**Comment by motokochan** [comment]
I generally recommend setting up things in "teams". You can have the bulk of people in a "developer" team with write access, but also have an "admin" team that has admin access to manage things. If you have one or two people you trust, it will make it a lot easier on you with management.

Also, I'd be happy to help too. I'm not too experienced in OS X development, but am fairly decent at reviewing submissions. That said, I'm fine if you'd rather I prove myself with a few PRs first.

**Comment by allejo** [comment]
Using teams is definitely the way to go :+1:

**Comment by jadengore** [comment]
Thanks guys for this awesome discussion! Also big thanks to @kbhomes for responding and making this happen.

Closing this issue, and hopefully many more soon! :smile:
