### ISSUE TITLE
Many issues on El Capitan

### ISSUE THREAD

**Issue by oliverh72** [radiant-player/radiant-player-mac#372]
There's so many, it's hard to list. This is v1.4.1 - sorry if the below is not specific. This is mostly a referral to the older fork, which I recommend using as it seemingly has less issues.

- interface refreshes when clicking on song title in queue
- blank screen when viewing album or playlist
- mini player doesn't update consistently

This fork w/fixes of 1.4.0 works MUCH better on El Capitan in my experience. 

https://github.com/jacobwgillespie/radiant-player-mac/releases/tag/v1.4.0

Thanks to both @kbhomes and @jacobwgillespie

**Comment by chrismou** [comment]
Hey @oliverh72 - I know this is an old issue, but there's been a ton of fixes/improvements in the past 2 months.

If possible, could you check latest code and see if you're still seeing the issues you're reporting here?  You can either build from master, or for convenience I've tagged a release on my fork of everything up to today: https://github.com/chrismou/radiant-player-mac/releases/tag/v1.5.0-20151213

Thanks!
