### ISSUE TITLE
Black layout styling needs adjustment on album view

### ISSUE THREAD

**Issue by dcp3450** [radiant-player/radiant-player-mac#376]
Looking at an album using the black layout the tracks are the wrong color and can only be seen when hovered over or playing.
<img width="1068" alt="player-error" src="https://cloud.githubusercontent.com/assets/408527/10548184/f13d2784-7406-11e5-805d-109f0db8ed1d.png">

**Comment by IanMcNelly** [comment]
Check out issue https://github.com/kbhomes/radiant-player-mac/issues/373

Has an open PR, and a fix for the CSS in the comments if you want to patch it yourself

**Comment by kbhomes** [comment]
Closing this because I've merged #374.
