### ISSUE TITLE
Flash requirement

### ISSUE THREAD

**Issue by luissquall** [radiant-player/radiant-player-mac#38]
A Requirements section in the README would be very helpful. Something like this:
- Adobe Flash Player for Mac OS X (http://get.adobe.com/flashplayer/)

As Adobe Flash Player is directly integrated with Google Chrome and enabled by default, and Chrome is my main browser, I had to download and install the Flash Player from Safari.

I tried to download the player from the WebView but I couldn't.

**Comment by Ecleptic** [comment]
Just came accross the same issue. I tried clicking the link Radiant provided and it went nowhere.  Downloaded it from Safari without any problems and was up and running in 2 minutes. 

This is a wonderful app. Thanks and keep it up!

**Comment by hamish9** [comment]
I use a separate account for admin functions so maybe that is why things weren't as seamless. Here is what I did to get the player working in El Capitan 10.11.13.
I came across the flash not installed issue, clicked the download button and nothing downloaded. I then manually installed the latest version of Flash Player for Mac, tried again, still didn't work even after reboot. Next I went to: System Preferences -> Flash Player -> Updates. The NPAPI plugin was not installed. I clicked the link to install, installed the dmg, tried again and it worked.

**Comment by aljex** [comment]
There is no such Flash Player icon anywhere in my System Preferences.

I have El Capitan 10.11.6. When I check for updates it says no updates available, so I don't know how to get 10.11.13. Wikipedia says the last El Capitan was 10.11.6 and the current osx is Sierra 10.12.1 Perhaps 10.11.13 was a typo for 10.11.3 ?

In any event, I too, cannot use the app by following the directions.

The button that pops up to download flash does nothing.

The web interface works in chrome on the same laptop.

**Comment by tjanson** [comment]
Do you use Homebrew [1]? (If no, consider it — it's pretty cool.) You can
install the correct Flash plugin with `brew install flash-npapi`. Otherwise
see the comments in #615, which is also about installing Flash.

[1]: https://brew.sh

>

**Comment by aljex** [comment]
I do use homebrew, and it's both cool and uncool. Expecting users to chown
/usr/local/* to a user account is so wrong as to make it almost unusable,
no matter how convenient most other aspects are. Working around that
idiocity almost counters that convenience. But I can work around that so
I'll try flash-npapi. Thanks.
