### ISSUE TITLE
Media keys broken?

### ISSUE THREAD

**Issue by lhickin** [radiant-player/radiant-player-mac#381]
I'm not sure if this was a result of some sort of update or the fact that I installed the play music extension in Google Chrome but my media keys do not work anymore.

I uninstalled the extension in chrome to stop the hijacking of my media keys but Radiant Player still won't respond to pause, previous, or next no matter whether it is the active window or not.

After uninstalling the extension iTunes began working as expected with the media keys, so they are not physically broken.

By the way, great app. I use it daily and there's nothing out there like it, thank you so much!

**Comment by planetmadness** [comment]
I have the same issue. since this morning media keys are broken. Did not even have the play music extension installed.

**Comment by ztoben** [comment]
Also having this issue. No play music extension installed.

**Comment by philhess** [comment]
Same issue here.  They were working fine before the latest OS X update 10.11.1     
Also a refresh issue with the app,  if it locks up,  resize the window and it will be good again.

**Comment by Dakar-A** [comment]
Same issue, on Radiant Player 1.4.1 and OSX 10.11.1

**Comment by Squintz82** [comment]
Same here OSX 10.10.5

**Comment by lhickin** [comment]
I also recently updated to 10.11.1 if that is any help

**Comment by megalithic** [comment]
wow, i literally have been sitting here trying furiously to get the keys working again, didn't realize others were affected. 

pulled down beardedspice's source and found that they are using the SPMediaKeyTap lib, while radiant-player is not. beardedspice's works. what's also interesting, is that when both apps are loaded (a tab is loaded with google music and actively playing; and radiant player is running with music music playing) key events are captured by radiant-player, but fail to execute. once you exit radiant-player the keyevents continue working in bearded spice.

anyway, i'm going to investigate adding in SPMediaKeyTap and see if that works.

**Comment by megalithic** [comment]
EDIT: fixed. working on getting a PR up (first time with ObjC or swift, so go easy on me). thankfully the change was in my preferred language (JavaScript). google changed their polymer (presumably?)/web component elements from `sj-icon-button` to `paper-icon-button`. cc @kbhomes

**Comment by lhickin** [comment]
Thanks man. Changed the name of the web component elements and re built it, works perfect!
I spent way too long trying to figure out what was going wrong until I read your comment

**Comment by chrismou** [comment]
(thumbsup) Cheers dude, works for me

**Comment by ztoben** [comment]
Works for me as well. Thank you!

**Comment by philhess** [comment]
Can someone explain how I can apply this fix?  Thanks.

**Comment by Squintz82** [comment]
Is there an new app build?

**Comment by megalithic** [comment]
@philhess @Squintz82 for now, y'all will have to pull the source code down and build it from my repo/branch within xcode, OR, pull the source down and make the changes in main.js yourself and build (that way you don't have to worry with using my forked repo/branch/sha).

short answer is, build it yourself until @kbhomes and team can merge in the fixes.

**Comment by philhess** [comment]
Ok thats what I assumed,  Ill just wait for the merge.  Thanks and glad its fixed.

**Comment by Nixon506E** [comment]
It's pretty easy to just go to the application and right click and select 'show components.'  At that point just follow the directories from resources to js and open up main.js.  Inside 'main.js' you can replace all instances of sj-icon-button with paper-icon-button.  Then just refresh the page and it should be good to go!

**Comment by philhess** [comment]
Yep that was easy and works.  Thanks!!

**Comment by tjkirch** [comment]
Thanks megalithic and Nixon506E!  I edited main.js and s/sj-icon-button/paper-icon-button/g and I'm back in business!

**Comment by kbhomes** [comment]
Many thanks to @megalithic! This is now fixed in master (bb13b70ac672bf82c51aa712392010461198ce13) and will be available in the upcoming release.
