### ISSUE TITLE
Google took our navigation buttons

### ISSUE THREAD

**Issue by shawn-mitch** [radiant-player/radiant-player-mac#385]
In the latest Google Music update, besides changing element tags which is messing with the JS and CSS, Google also took out the forward and back keys. Anyone know how difficult it would be to hack them back in? Or does someone have a better idea?

**Comment by kbhomes** [comment]
This is fixed in bb13b70ac672bf82c51aa712392010461198ce13 which I just pushed, turns out it's the same issue of the tag name being changed.
