### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrismou** [radiant-player/radiant-player-mac#386]
It may be worth adding a CONTRIBUTING.md file to the repo, even if it's just with a few loose guidelines on how to prepare to put in a pull request.

I know that a barrier to contributing for some devs is not being 100% versed in the language/app, and despite knowing how to fix a bug, they avoid it because they're worried about not doing it to the right standard, etc. Getting a few points down might help encourage people to chip in if they know what the minimum requirements are.

Added bonus is Github recognises the file and highlights it to potential collaborators.  https://github.com/blog/1184-contributing-guidelines

Is it worth me putting together a working draft, and you guys can pick it apart till we get something everyone's happy with?

**Comment by jadengore** [comment]
@chrismou :+1:, let me know what you come up with,

**Comment by kbhomes** [comment]
@chrismou Absolutely, that would be wonderful!

**Comment by motokochan** [comment]
Sounds like a great idea.

**Comment by jadengore** [comment]
@chrismou Any update on this draft?

**Comment by chrismou** [comment]
@jadengore Been looking into this https://github.com/radiant-player/radiant-player-mac/issues/388#issuecomment-151875245 -- I'll aim to get a draft up in the next day or so

**Comment by chrismou** [comment]
First draft is up: https://github.com/radiant-player/radiant-player-mac/pull/401

I'll close this issue now - feel free to post any feedback you have on the PR :-)

@jadengore @jacobwgillespie @kbhomes @motokochan @benburton
