### ISSUE TITLE
Media keys do not work

### ISSUE THREAD

**Issue by afunix** [radiant-player/radiant-player-mac#387]
The media keys on Mac keyboard do not pause/play/switch tracks anymore.
I'm not sure when did it started. Probably since upgrade to El Capitan (10.11.1), or latest System Update, or the latest version of Radiant Player (1.4.1).

I don't have any idea how to debug the issue or which logs to collect.

**Comment by thenitai** [comment]
Same here. Doesn't work anymore.

**Comment by vincentdieltiens** [comment]
I'm still on Yosemite with 1.4.1 and had the same problem.

**Comment by chrismou** [comment]
This was fixed in #381 - if you pull master and build your own binary in Xcode you can get hold of the fix immediately, otherwise it should in the next release.
