### ISSUE TITLE
Some elements not correctly styled with the Black theme

### ISSUE THREAD

**Issue by Delallen** [radiant-player/radiant-player-mac#391]
Within the new app v 1.4.1, some screens and elements aren't correctly styled for the black theme. 

![screenshot 2015-10-29 11 24 47](https://cloud.githubusercontent.com/assets/982029/10823081/5ba35f66-7e30-11e5-93df-c8c43bcf6c27.png)

**Comment by lausse** [comment]
+1

**Comment by MarshallOfSound** [comment]
Hopefully part of #388

**Comment by kbhomes** [comment]
Correct! The release is out now that fixes these issues.
