### ISSUE TITLE
Media keys not working in 10.11.1 (El Capitan)

### ISSUE THREAD

**Issue by jacobgraf** [radiant-player/radiant-player-mac#393]
None of the media keys work. Doesn't matter if it's in the foreground or background. None of them seem to do anything.

Spacebar does pause and arrow keys left and right do work, but I can't get the native Mac keyboard media keys to work.

**Comment by jacobwgillespie** [comment]
Google updated their element names, so we had to adjust - this has been fixed in bb13b70ac672bf82c51aa712392010461198ce13 (and subsequent commits) and should go out as part of 1.5.  Keep an eye on #388 for progress.

**Comment by jacobgraf** [comment]
Great! Thanks man!
