### ISSUE TITLE
Mini player on El Capitan does not update track information

### ISSUE THREAD

**Issue by kbhomes** [radiant-player/radiant-player-mac#394]
The mini player on El Capitan just needs work in general. Somehow did not catch this before the release I just pushed out.

**Comment by jacobwgillespie** [comment]
This might be related to #400

**Comment by DefenestrateMe** [comment]
This isn't just affecting El Capitan, I'm also experiencing it on Yosemite.

**Comment by dmlogs** [comment]
I'm on Yosemite using 1.5.0 - controls and song position are working, but no track information in the mini player

**Comment by chrismou** [comment]
Confirmed fixed in master - should be available in the next release (or now if you fancy building from source) so closing this ticket for now
