### ISSUE TITLE
Moving windows on El Capitan

### ISSUE THREAD

**Issue by ollien** [radiant-player/radiant-player-mac#395]
Moving the window in Radiant has become a bit of a chore. Often when I drag the top, I begin selecting text within the website.

**Comment by chrismou** [comment]
I'm seeing a similar issue. Hardly noticeable if you move the window slowly, but as soon as you try to drag it at any sort of speed, it starts to lag and I end up with the search box highlighted

**Comment by planetmadness** [comment]
This is also an issue while starting Radiant, as it is always positioned in a different place than I'd like to have it, I have to wait until Radiant is fully up and running to be able to drag the window at all.

**Comment by rahulh** [comment]
I have in on El Capitan that I cannot move the window at all (using 1.5.0)

**Comment by smackjack3** [comment]
Same here. I'm on El Capitan and 1.5.0 and sometimes I can't move the window at all.  It seems that this is only the case when I either don't have Chrome, or I have it open but am using a different account than the one I use for my Google Music subscription.  Once I switch accounts or open another Chrome window with my personal Google account (which is what's subscribed to Google Music) then I can move the window with ease.

**Comment by andrevabo** [comment]
Same here. Can't move the window at all. Tried with Chrome open and closed, but nothing changes.

Version 1.5.0 running on 10.11.1

**Comment by jacobwgillespie** [comment]
The app itself uses an embedded webview, which is closer to Safari than Chrome - if I get some time later today I'll take a look and see if I can find anything.

**Comment by aztlan2k** [comment]
i find that i can move the window if i've clicked in another window (say a open chrome window) and then click-and-drag the radiant window. (i.e., so the radiant window gets focus and immediately starts being dragged in one action)

If I do it as separate actions (click to focus radiant window + click-drag to try and move the window) it doesn't work.

**Comment by jacobwgillespie** [comment]
So, Google updated their element names again.  #413 should enable dragging as it was previously implemented.

IMO we should look at alternate implementations - two ideas for further research:

* implement something like `-webkit-app-region: drag` from Electron
* implement the app bar in native code

**Comment by seniortwinkie** [comment]
I have found that if Radiant player is not in focus (like if I click on my desktop first) I can move the window without problem, but as soon as it has focus, it just selects the text.

OS X: 10.11.2
Player: 1.5.0

**Comment by jacobwgillespie** [comment]
This is fixed in master and should go out today or tomorrow as 1.6

**Comment by davidhellmann** [comment]
Hm, same problem here. Newest Version. Can't move the window.
