### ISSUE TITLE
v1.5 crash when checking last scribbled items from last.FM

### ISSUE THREAD

**Issue by nivong** [radiant-player/radiant-player-mac#396]
When you click on the icon on the top right (red last.fm icon) the app will crash.

**Comment by chrismou** [comment]
I have a pull request in to fix this: https://github.com/radiant-player/radiant-player-mac/pull/389. Hopefully it should be sorted in the next release

**Comment by schmeat** [comment]
I have also noticed that scrobbling does not seem to work with 1.5.0.

**Comment by chrismou** [comment]
@schmeat This one should be fixed by https://github.com/radiant-player/radiant-player-mac/pull/400

Looks like we've had a couple of issues with the last.fm API and Google updating their web player that caused a few things to stop working. We should have these both sorted in the next release.

**Comment by schmeat** [comment]
@chrismou Sounds good, thank you.

**Comment by chrismou** [comment]
https://github.com/radiant-player/radiant-player-mac/pull/400
