### ISSUE TITLE
Notifications don't display in El Capitan

### ISSUE THREAD

**Issue by ollien** [radiant-player/radiant-player-mac#398]

**Comment by jacobwgillespie** [comment]
The JS code reporting plays is currently broken - PR #400 combined with #389 should resolve.

**Comment by ollien** [comment]
Thanks!

**Comment by dmlogs** [comment]
Assuming the pull requests will resolve for Yosemite as well, but thought I would log my issue as well,

no notifications are displayed for Yosemite using v1.5.0

**Comment by chrismou** [comment]
Confirmed fixed in master - should be available in the next release (or now if you fancy building from source) so closing this ticket for now
