### ISSUE TITLE
Albums and artists unresponsive after closing window

### ISSUE THREAD

**Issue by robert-barrie** [radiant-player/radiant-player-mac#403]
After you hit the red 'close window' button top left, all hell breaks loose. After summoning the window back, pages appear to be frozen – album pages in particular. The 'Listen Now' pages seems to be unaffected.

**Comment by FezVrasta** [comment]
I've noticed it as well, it get fixed if you resize the page (as workaround)

**Comment by chrismou** [comment]
This should essentially be fixed in 1.7.  If you're still experiencing issues, feel free to open another ticket
