### ISSUE TITLE
Radiant Player blocking automatic restart for updates

### ISSUE THREAD

**Issue by swrobel** [radiant-player/radiant-player-mac#405]
I've been installing the latest OS X 10.11.2 betas and each time, automatic restart is prevented by Radiant Player. It isn't playing music, just running. Anyone else seeing this behavior?

**Comment by mohnjatthews** [comment]
Radiant Player seems to be having a hard time closing, even when right clicking on it in the dock and selecting quit. Force Quitting the app seems to work for now though.

**Comment by akrs** [comment]
It looks like it won't respond to quitting from the dock or from the OS requesting it to from a system shutdown. However, it is still responsive and quitting from the Radiant Player menu or with cmd-Q works fine.

**Comment by chrismou** [comment]
I don't have the beta, but can confirm I'm seeing this on 10.11.1.  Strangely, you don't even get a prompt to close the app - it just seems to hang. Though for me, going to the menu and selecting Quit Radiant Player seems to work OK, and shutdown happens immediately after.

**Comment by Squintz82** [comment]
Same issue on 10.11.1
