### ISSUE TITLE
Tray menu shows "No song currently playing" when a song is playing

### ISSUE THREAD

**Issue by imcdonagh** [radiant-player/radiant-player-mac#406]
<img width="1171" alt="screen shot 2015-11-06 at 9 12 39 am" src="https://cloud.githubusercontent.com/assets/10691168/11003325/9f2f498e-8466-11e5-830b-505d8744e943.png">

**Comment by YungArthur** [comment]
I'm also experiencing this issue on the latest version of OS X and Flash Player.

**Comment by imcdonagh** [comment]
Yes that's right. I'm on El Capitan as well.

**Comment by talfanevans** [comment]
Also experiencing this issue. Yosemite 10.10.4 (14E46)

**Comment by chrismou** [comment]
It looks like this'll be sorted once https://github.com/radiant-player/radiant-player-mac/pull/400 is merged

**Comment by YungArthur** [comment]
The issue has been fixed. Thanks! :+1:

**Comment by jacobwgillespie** [comment]
Closing this for now - it will go out on the next release.
