### ISSUE TITLE
Scrolling and UI freeze Issues

### ISSUE THREAD

**Issue by YungArthur** [radiant-player/radiant-player-mac#408]
Sometimes I'm unable to scroll when using Radiant Player. It seems to happen spontaneously - although I've noticed that this issue happens when browsing "top charts" and artist pages. I'm on OS X El Capitan and I'm also using the latest version of Flash Player.

I can avoid getting stuck in this by clicking on "my library" or "new releases".

**Comment by andrewsawczyn** [comment]
Glad I'm not the only one.  Radiant has been almost unusable for me for awhile.

**Comment by YungArthur** [comment]
Oh, we just need someone to merge then?

**Comment by andreis** [comment]
Same issue. It's just the UI freezing I guess, if you select something you can see it actually keeps working, you just don't get any feedback.

**Comment by chrismou** [comment]
OK, I see this now.  I can't seem to trigger the issue, but if I leave the player open for a while (on a different workspace, but I don't know if that's relevant) the UI seems to freeze.  Although as @YungArthur says, clicking My Library seems to fix it, randomly.

Hope you don't mind, I'm doing to update the ticket title slightly to remind me of the issue.  I'll leave the app open for a while over the weekend in debug mode and see if I can see any reason why it might be happening.

**Comment by alexcarruthers** [comment]
On restart of the computer, everything works smoothly.
But after a while it starts to slow down (especially next day).
And the further you go down into the menus, the worse it becomes.

**Comment by alexcarruthers** [comment]
Also, looking at the suggestion made in https://github.com/radiant-player/radiant-player-mac/issues/403, resizing the window seems to bring it back to being smooth

**Comment by v1nsai** [comment]
Just downloaded the app for the first time, and the scrolling is really bad.  Resizing the window has no effect.  I'm on OSX Yosemite.

Seems to use a lot of CPU too, even for a Flash app.  If there's any log files or any other way I could help fix this I'll gladly submit them.

**Comment by jscheel** [comment]
I'm getting horrible scrolling performance. I'm thinking it might have something to do with the background that scrolls in parallax with the page. I'm on a retina screen, which I know has some performance issues around certain background positioning.

**Comment by jacobwgillespie** [comment]
Are you getting the same performance issues on Safari?

**Comment by jscheel** [comment]
@jacobwgillespie nope, safari runs fine. Also the header appears cut off in radiant player. I actually don't think there is any parallax, it may just be the significant lag in repainting the background.

**Comment by andreis** [comment]
:+1: 

Overall very serious lagginess and responsiveness problems, that briefly go away after window resize.

**Comment by jadengore** [comment]
We are working on it. It seems that Radiant Player over time uses up a bunch of memory that causes the application to freeze and have non-responsive UI after a couple of days. Radiant 2.0 will hopefully address a lot of these issues.

**Comment by jscheel** [comment]
That's awesome to hear. Just as a side note, for me, the lagginess happens
immediately. There's no need to spend time using the app. It's instantly
laggy when I first open it.

**Comment by andrewsawczyn** [comment]
My experience is the same as jscheel, it's laggy immediately.   Maybe we're discussing two different issues?

**Comment by leemm** [comment]
Mine works fine until I minimise the app to dock.  Restoring it stops the ui rendering.  Minimising and restoring updates the display.

**Comment by jscheel** [comment]
Interesting feedback. I upgraded from Mavericks to El Capitan over the weekend. Now scrolling performance is perfectly fine. However, I also now see the issue @leemm mentioned.

**Comment by robert-barrie** [comment]
The issue @leemm mentioned still persists in the latest two updates. Is this being looked into?

**Comment by Mossop** [comment]
For me the UI is almost totally frozen as long as the playlist pop-up is displayed. Hiding it makes everything work again

**Comment by leemm** [comment]
There are workarounds.
1/ If you restore the app from dock and then resize the window it starts funtioning again.  In fact this works for any time the gui locks.
2/ To move the window in El Capitan click the desktop to change focus then it should be ok.  At least until next time you do something.

**Comment by chrismou** [comment]
The originally reporting issue should essentially be fixed in 1.7.  If you're still experiencing issues, feel free to open another ticket
