### ISSUE TITLE
Cant create playlists in radiant player

### ISSUE THREAD

**Issue by MWhyte** [radiant-player/radiant-player-mac#411]
Hi,

Firstly well done for the app its awesome.

I have noticed that I am unable to create playlists in radiant player. Attempts to create, open the create dialog box. I can click create but the playlist doesn't show in the sidebar and if I login to the google play music website the playlist isn't their either.

Inversely I can create on the google play site and reload radiant to see the playlist. I can also dlete playlists from radiant just can create them.

Thanks

**Comment by MWhyte** [comment]
Tested this on Yosemite and el captian.

**Comment by chrismou** [comment]
Dump of console when clicking to create a playlist:

```
[Error] CustomError: Error in protected function: null is not an object (evaluating 'pM')
	c
	(anonymous function)
[Error] CustomError: Error in protected function: null is not an object (evaluating 'this.fD.focus')
	c
	(anonymous function)
	dispatchEvent
	fire
	_finishRenderOpened
	_onNeonAnimationFinish
	handler
	dispatchEvent
	fire
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	(anonymous function)
	forEach
	(anonymous function)
	c
```

After clicking create:
```
[Error] CustomError: Error in protected function: null is not an object (evaluating 'this.fD.value')
	c
	(anonymous function)
```

**Comment by kazak1377** [comment]
I think, this bug not in radiant player itself. It's in safari engine. I getting this in safari too. May be google made this to stimulate using chrome. I don't know. But this error is quite recent.

**Comment by chrismou** [comment]
Good spot - I'd not noticed that before. Been using Chrome for too long.

I've logged a ticket on their support forum. Though I doubt I'll get a definitive response - that forum seems to be where issues go to die.

https://productforums.google.com/forum/#!topic/play/qmTJ-ZvjKC4

**Comment by jacobwgillespie** [comment]
Closing since this is an external bug
