### ISSUE TITLE
Keyboard shortcut for search doesn't work

### ISSUE THREAD

**Issue by Penderworth** [radiant-player/radiant-player-mac#412]
At the moment, the keyboard shortcut for Search is not working. `⌘ F` is assigned to it, but it doesn't activate the search bar as expected. The shortcut actually doesn't seem to do anything at all.

Also, pressing the `return` key to search works as expected, but also activates the alert sound set for OS X as if something didn't work properly.

**Comment by jacobwgillespie** [comment]
This should be fixed by #413
