### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by jacobwgillespie** [radiant-player/radiant-player-mac#414]
Mainly for @radiant-player/radiant-player-mac, but let's create some docs around the release process.  Who does releases, when can they happen, are we signing builds, etc.  This probably specifically involves @kbhomes.  I'd vote for a `docs` folder with a `RELEASE.md` that describes what has to happen.

**Comment by nivong** [comment]
I vote for a release every week with fixes, it's still not great. And a dev/nightly branche that gets build automatically every night

**Comment by chrismou** [comment]
We've been fairly efficient with pull requests and merges recently. Unfortunately, that doesn't include official "app store" releases, which @kbhomes has ultimate control over.

Perhaps an idea would be to tag after every fix, and do a Github release after. I only realised recently that you can associate releases with tags, and upload an accompanying binary.

So the process could be:

- Pull request is approved & merged
- Person doing merge tags new version (bug fix release - ie, 1.5.0 to 1.5.1)
- Same person builds binary locally. Creates release associated with tag. Uploads binary.

That way when people come here to report problems already fixed, at least we have a pre-built binary to point them at.

From that point, it could then be up to @kbhomes to do his major App Store release, at which point he would (most likely) bump the version up as a minor release (ie 1.5.1 to 1.6.0).

I prefer to keep things SemVer wherever possible, and this would mean that (potentially) new features would be going in as bug fix releases, but this would only be a temporary measure until @kbhomes gets enough free time to get back into the swing of things.

Only thing I'm not 100% sure about is where in that process you'd bump the version number in the code. We don't want the pull requests including version bumps as that could get messy/confusing, so it would need to happen after the merge, but before the tag.

**Comment by jacobwgillespie** [comment]
I like SemVer as well, though I'll have to think through what it means for a desktop app (i.e., what is a "breaking change" exactly).

For the release process, the app isn't in the app store (as in the Mac App Store) - it updates with the Sparkle framework, which reads from an XML file on our website (source at https://github.com/radiant-player/radiant-player-mac/blob/gh-pages/appcast/appcast.xml) and uses that to download updates.

IMO the ultimate nicety would be for this thing to build on Travis, update a development binary someplace with the output of every successful build, and do an automated GitHub / Sparkle release whenever we tag with a particular syntax (i.e. `v0.0.0`).  That means setting up Travis and writing a bunch of scripts for properly generating the changelog and updating the website (`gh-pages`) after every tag.  Also on that topic - we would need to maintain a changelog.

For the actual Sparkle release, there's an included DSA signature.  I haven't checked yet, but I'd assume that means asymmetric encryption and that means that @kbhomes has the private key.  Not sure how that'd work with the Travis build idea, though theoretically we could pass in the private key as an encrypted Travis environment variable.

Upsides:

* Travis manages all releases and it's as simple as a `git tag`
* Releases (presumably) happen more often

Downsides:

* Anyone with contributor-level access to this project could extract the private key and potentially push malicious software with a malicious pull request
* Greater chance of accidental release

**Comment by chrismou** [comment]
I think for a desktop app, I'd sway towards classing it as:

1.0.x - bug fix
1.x.0 - new feature
x.0.0 - pre-decided "milestone" release

The last one is a bit eroneous really. Its just a case of everyone saying you know what, there's a load of new features, let's call it a milestone. Like knocking off all the proposed issues on @jadengore's 2.0 milestone list, for example.

Up for debate obvs. But that's probably how I'd categorise it.

Good point about the App Store. I think I'm losing it - I could have sworn I found it on the app store originally, but I must have been dreaming. I've been using a custom build for so long now!

**Comment by jacobwgillespie** [comment]
I've started to add some release docs and scripts in #416 - feel free to take a look and comment.  I'm still working and will get everything cleaned up closer to completion.

**Comment by brendonrapp** [comment]
I really wish I could just pull and build the latest HEAD via Homebrew Cask.

**Comment by jacobwgillespie** [comment]
Follow along on the actual Travis build process at #449

**Comment by jacobwgillespie** [comment]
This is ready for review at #449
