### ISSUE TITLE
Can't move window

### ISSUE THREAD

**Issue by vcao** [radiant-player/radiant-player-mac#419]
Can't drag window around and move it around the desktop. Version 1.5

**Comment by jacobwgillespie** [comment]
This is fixed in #413 and should go out on the next release.

**Comment by acondiff** [comment]
Having the same issue. Good to know it's being fixed. And Jacob, funny bumping into you here! :)

**Comment by jacobwgillespie** [comment]
Hey Austin!  Yep, funny bumping into you too - hope all is well!
