### ISSUE TITLE
"Listen Now" overlap in header + search area

### ISSUE THREAD

**Issue by niffyat** [radiant-player/radiant-player-mac#421]
The "Listen Now" text overlaps with the search field area. There appears to be quite a bit of empty space available though, maybe the minimum padding to the right of "Listen Now" could be adjusted? 

![screen shot 2015-11-23 at 8 06 50 pm](https://cloud.githubusercontent.com/assets/887476/11357633/1124741e-921e-11e5-819a-5c1d1f40a335.png)

(also sorry if this is a dupe, i searched for "listen now" and couldn't find anything)

**Comment by jacobwgillespie** [comment]
I believe this has been fixed in #418 and will go out on the next release.

**Comment by niffyat** [comment]
Awesome, thanks for the quick reply! :)
