### ISSUE TITLE
Multiple calls to last.fm api at start of every song

### ISSUE THREAD

**Issue by chrismou** [radiant-player/radiant-player-mac#425]
main.js calls GoogleMusicApp.ratingChanged(MusicAPI.Rating.getRating()); within a mutationObserver.

This makes several calls to the last.fm api to love or unlove the track, depending on whether it's been thumbed up or not (if you have the "love a track on last.fm when rated thumbs up" option checked).

The main issue around this has been fixed (https://github.com/radiant-player/radiant-player-mac/issues/390) but for the sake of efficiency, it would be good to get to the bottom of why it's called so many times and cut it down to only run when the track rating is changed

Follows on from https://github.com/radiant-player/radiant-player-mac/pull/426

**Comment by chrismou** [comment]
Note to self:  we're not losing loved tracks, but it does seem the unloving/reloving unexpectedly.

http://www.last.fm/user/chrismou/loved

Looking at this, for about 40 minutes on the 23/12 it did the unlove/relove thing so now they're showing at the top of the list.

**Comment by jacobwgillespie** [comment]
This has been resolved by the switch to gmusic.js.
