### ISSUE TITLE
thumbs not reflected in control bar

### ISSUE THREAD

**Issue by zobier** [radiant-player/radiant-player-mac#429]
![image](https://cloud.githubusercontent.com/assets/1370034/11521504/e478757a-9900-11e5-8838-2851fc3492f4.png)

I expected the thumb icons in the control bar (on rollover) to reflect my likes.

v 1.5 mac

**Comment by jacobwgillespie** [comment]
Yep, I can confirm this one - we need to see if this is an issue with our custom CSS or with Google's webcomponents.js in webkit.

**Comment by chrismou** [comment]
Looks to be the CSS. Thumbed up tracks do have an icon="sj:thumb-up-outline" set on the button, so it'll just be a case of tracking down what's triggering the style change.

I'll look into it

**Comment by chrismou** [comment]
Hmm, maybe not. The button's an SVG and it looks like it *is* being triggered by the JS. Interesting way of doing it.

**Comment by chrismou** [comment]
Think I've got it sorted on dark & light themes. Feel free to check over the PR (#436) when you get a few minutes.
