### ISSUE TITLE
Apple EarPods button doesn't pause/resume music

### ISSUE THREAD

**Issue by ertemplin** [radiant-player/radiant-player-mac#43]
When I use the headphones that came with my iPhone to listen to music with this app and press the button, iTunes opens instead of the music being paused.

The behavior should be:
Single press: pause
Double press: next song
Triple press: previous song

@kbhomes I'll look at this over this weekend and see if it's easy to implement. If so, I'll send you a pull request.

**Comment by jadengore** [comment]
@afunix This works great for my needs! Thanks!
