### ISSUE TITLE
Mini Player not showing any song info

### ISSUE THREAD

**Issue by haofeng93** [radiant-player/radiant-player-mac#437]
I can't seem to see any information displayed in the Mini Player. I updated Flash Player, and I'm running the latest OS X and Radiant Player 1.5.0. I've played with most of the settings to see if I can fix it, however nothing seems to help. As such, I never get any notifications when the song changes.

Also, I have issues of;
- Not being able to quit the app from the Dock (pressing Quit does nothing)
- Text takes a long time to load when I first start the app
- If Radiant Player isn't used in full screen, whenever I open albums, nothing will display, or the app will freeze

I only bought this Mac two days ago, so I'm not sure why I'm experiencing these issues.

Thanks!

**Comment by jacobwgillespie** [comment]
These issues are fixed in master - we need to push a release out soon.  If you want to build from master feel free, and I'll try to get the release coordinated ASAP.
