### ISSUE TITLE
Mini Player: 'No song currently playing' when song is playing

### ISSUE THREAD

**Issue by acondiff** [radiant-player/radiant-player-mac#440]
I get the message 'No song currently playing'  in the mini player whenever I have a song playing. The controls in the mini player still work and the play head even moves across the track. No album art either.

**Comment by chrismou** [comment]
Hey @acondiff - same as your other issue, this was fixed in #400 and should be included in the next release. 
A ton of stuff broke when Google made some unexpected changes. One change at our end seemed to fix them all
