### ISSUE TITLE
Magical shrinking nav buttons

### ISSUE THREAD

**Issue by shawn-mitch** [radiant-player/radiant-player-mac#442]
![screen shot 2015-12-11 at 9 39 05 am](https://cloud.githubusercontent.com/assets/5890308/11748058/01e09664-9fec-11e5-8625-96eaee497d44.png)

The nav arrows change size when the window resizes. This seems like a somewhat neat idea in theory but the execution needs work. At around 1100px wide and under, the arrows are at their smallest, which looks pretty bad. The hit boxes are still big enough that they're still functional but it's still annoying.

**Comment by chrismou** [comment]
Fixed in #443, courtesy of @davepagurek
