### ISSUE TITLE
Interim release

### ISSUE THREAD

**Issue by chrismou** [radiant-player/radiant-player-mac#448]
@radiant-player/radiant-player-mac 

We should look at getting an interim release out the door until we hear back from @kbhomes . Annoyingly, I'm coming across reddit threads where Radiant is being recommended and immediately dismissed because it's "broken" - referring to stuff that's been fixed for a month and a half.

I don't think we can push updates out to existing users, but we can at least tag a release, update the main site with the new link and stop putting off new users.

Any issues with this?  If not, I'm going to start prepping a 1.6.0 release tonight.  @jacobwgillespie - is there anything your deployment stuff can do at this point?  Or is it still hinging on the bot being added to the contributor list?  Right now I'm just interested in tagging what we have, doing a Github "release" and updating the download link.

In the meantime, I'll cross check the changelog to make sure everything's there, and do some prep on the release notes.

**Comment by jacobwgillespie** [comment]
I heard back from @kbhomes and he's planning to add a few of us as org admins, so once that's done we can add the bot user and I can wrap up automatic builds...  I'd say that we should probably hold off on an interim release as we should have access very soon.

**Comment by jacobwgillespie** [comment]
Okay, we have access, @radiant-bot has been added, and we have the Sparkle signing private key (just pushed it to #449).  

Remaining todos:

- [ ] #435 has to land
- [ ] I need to wrap up the scripts for building / deployment

**Comment by chrismou** [comment]
I should be home in a couple of hours. If noone bears me to it, I'll test it then.

Good times! :+1:

**Comment by jacobwgillespie** [comment]
Okay, so now I need to wrap up the build / deploy scripts.  I should be able to get to that tomorrow and after it's reviewed we can push out 1.6!

**Comment by chrismou** [comment]
\o/
