### ISSUE TITLE
Title not correctly set 

### ISSUE THREAD

**Issue by patrickhpan** [radiant-player/radiant-player-mac#458]
The DOM id of the title field has changed from "#player-song-title" to "#currently-playing-title". Thus, the title is no longer correctly updated in notifications or through the scripting bridge.

The fix is simple—on line 252 of main.js, change "#player-song-title" to "#currently-playing-title".

**Comment by chrismou** [comment]
Hey @patrickhpan

This had already been fixed in #445 and should be available in the next release
