### ISSUE TITLE
Create New Playlist broken

### ISSUE THREAD

**Issue by JustinTBrown** [radiant-player/radiant-player-mac#467]
Create new playlist function appears to be broken. Whether triggering from sidebar playlists or through an individual track's contextual menu, it doesn't allow you add a playlist title or to even save an unnamed playlist.

Here is a screen shot of Radiant:
![screen shot 2015-12-21 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/1620519/11942085/6ee68482-a7f1-11e5-8709-bb54221c80d0.png)

Here's a screen shot using Google Play through Chrome:
![screen shot 2015-12-21 at 2 47 24 pm](https://cloud.githubusercontent.com/assets/1620519/11942148/e657bab8-a7f1-11e5-9c8c-9b3971d88de1.png)

I'm using Radiant 1.6.2

**Comment by chrismou** [comment]
Turns out this is an issue with Google Music in safari.  I can recreate this issue in a browser.

I've logged a ticket with Google Music about it, but I'm not expecting a swift resolution.

https://productforums.google.com/forum/#!topic/play/qmTJ-ZvjKC4
