### ISSUE TITLE
Thumbs up and track slider should be the same shade of orange

### ISSUE THREAD

**Issue by LabLayers** [radiant-player/radiant-player-mac#468]
Take a look at this screenshot and notice how the thumbs up and track slider are different shades of orange:

![image](https://cloud.githubusercontent.com/assets/607807/12011636/96a741de-aca4-11e5-82db-64854737da37.png)

These should be the same shade of orange.

**Comment by chrismou** [comment]
Slider uses apple's orangeColor value (ff9224) whereas rating buttons are images (fd8824)

I'll sort this in the new year. There's probably a few other images that will be slightly off colour too.

**Comment by chrismou** [comment]
Fixed in #476
