### ISSUE TITLE
Playlists not saving

### ISSUE THREAD

**Issue by waldo1979** [radiant-player/radiant-player-mac#477]
I just tried to save my "I'm feeling lucky" list and it's not persisting correctly.

**Comment by MarshallOfSound** [comment]
This is very unlikely to be a bug with `radiant` rather a network connection issue or a problem of Google Play Music itself

**Comment by chrismou** [comment]
Looks like Google music just doesn't work all that well on anything that isn't Chrome :-/  https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/play/qmTJ-ZvjKC4/9PH7OmmjCAAJ

**Comment by MarshallOfSound** [comment]
This is where a point at ChromiumEmbedded and leave the building :smile_cat:

**Comment by jacobwgillespie** [comment]
Which is where radiant-player-electron could come in handy...  :wink:

**Comment by waldo1979** [comment]
@MarshallOfSound I just confirmed that this isn't an issue with Google Play music. This problem is specific to the Radiant. Does the issue repo on your system?

Repo Steps:
1. Listen Now
2. I'm feeling lucky radio
3. Save
4. Create Playlist
5. Note that the playlist isn't created

Doubt it's a "network connection issue", but maybe you can elaborate on that one.

**Comment by chrismou** [comment]
@waldo1979 I've just followed your steps using Safari and the exact same thing happened.

What made you think it was specific to Radiant?

**Comment by MarshallOfSound** [comment]
I still don't think Google officially support any browsers other than Chromium based ones.  You might have to polyfill something GPM wants in Safari

**Comment by chrismou** [comment]
@MarshallOfSound Pretending you support all browsers is totally the same as actually supporting them all... https://support.google.com/googleplay/answer/2844198?hl=en  :confused:

**Comment by chrismou** [comment]
Closing as this is essentially a Play Music issue. Unfortunately there's not much we can do until Google fix their cross browser compatibility

We could look at switching to using Chromium in the future, but it's unlikely to happen any time soon
