### ISSUE TITLE
Flashing Scrollbars

### ISSUE THREAD

**Issue by jjanusch** [radiant-player/radiant-player-mac#478]
Every few seconds, the scrollbars will switch to a black theme and go back to a normal style. It seems to only occur when I am within a playlist and is completely fine when I am on other pages like Listen Now. The sidebar scrollbar, when it actually appears, does the same thing

![screen shot 2016-01-06 at 8 41 16 am](https://cloud.githubusercontent.com/assets/3516836/12146545/5d004c6e-b451-11e5-88e0-e660f814b86c.png)

I'm running Radiant 1.6.2 on OS X 10.11.2. I have custom themes disabled (though it happens with them enabled as well and in multiple themes). A restart of both Radiant and my system did not fix the issue. I have scrollbars set to always be on.

**Comment by chrismou** [comment]
I can't seem to reproduce this at all.  Is it still happening on the latest version (1.8.0)?  Are you doing anything specific to trigger it?  Does it happen all the time or is it sporadic?

**Comment by jjanusch** [comment]
I haven't been using Radiant, but the latest release does not seem to have this issue anymore

**Comment by chrismou** [comment]
:+1: Cheers for the info!
