### ISSUE TITLE
'Playing From' Window Unable To Be Opened

### ISSUE THREAD

**Issue by jcady** [radiant-player/radiant-player-mac#486]
After using Radiant Player for awhile, sometimes it will get into a state where it's impossible to open the 'Playing From' window (the pane that comes up when you click the bottom right button).  When I click the button, it highlights orange and the window quickly expands open twice and then disappears.  When clicked again, the button un-highlights and the window briefly appears to be collapsed.  This has happened to me quite a few times and occurs indefinitely until the player is restarted.

Here's a video of it in action:
https://youtu.be/v1HkXMIG9tY

**Comment by jacobwgillespie** [comment]
What OS X version are you using?  Also, are you experiencing this still in version 1.8.0?

**Comment by jcady** [comment]
I haven't experienced this in a month or so. It's possible it was fixed in one of the updates (I'm on 1.7.3).

**Comment by jacobwgillespie** [comment]
Cool, thanks for letting us know!
