### ISSUE TITLE
Cannot create playlists in Radiant

### ISSUE THREAD

**Issue by mgoldkamp** [radiant-player/radiant-player-mac#487]
I have to use the web browser or my phone in order to create playlists. If I try to do it in Radiant the playlist never shows up.

**Comment by chrismou** [comment]
Originally, the reason behind this was Google's poor support for Safari (which powers Radiant).

I've just spotted that it seems to be letting me create them now, and I've added a few tracks, so I'm guessing Google have resolved the issue at their end.
