### ISSUE TITLE
Getting "Missing Flash Player" error after update to 1.6.2

### ISSUE THREAD

**Issue by JakubMatejka** [radiant-player/radiant-player-mac#488]
Hi,
I updated app to version 1.6.2 and when I opened the app, I got message that Flash Player is Missing and I can't play music. Until then, with previous version, the app worked fine and I haven't seen the error. Reinstall didn't help.

I've noticed issue #335 but I think it's not the same case because the app update obviously caused this problem to appear, I didn't change any settings in Google.

Thanks for help.

**Comment by MarshallOfSound** [comment]
Have you tried updating flash?  Normally it pops up and tells you to download the flash player update in safari

**Comment by JakubMatejka** [comment]
Well, earlier I did try to click on "Download Flash" in that popup but nothing happened. But I just manually downloaded and installed Flash installation for Safari and it works. ;o) Probably the problem is that I don't use Safari but Chrome as my main browser so it did not get a chance to tell me there's an update for the plugin. Anyway, thanks a lot for your help.
