### ISSUE TITLE
White boxes over play bar obscuring now playing

### ISSUE THREAD

**Issue by dwasyluk** [radiant-player/radiant-player-mac#493]
As of v1.6.2 there are these white boxes in the Radiant Player blocking access to thumbup/thumbdown and generally making it look like an eyesore. If you resize the window, the boxes appear to stack. Haven't found a way to remove them. Mac OSX 10.10.5.
![screen shot 2016-02-02 at 3 11 57 pm](https://cloud.githubusercontent.com/assets/987186/12762867/569b8b1c-c9bf-11e5-9a77-93b5760caad0.png)
![screen shot 2016-02-02 at 3 12 05 pm](https://cloud.githubusercontent.com/assets/987186/12762871/582db5ae-c9bf-11e5-8c65-acf3f66afd22.png)

**Comment by dwasyluk** [comment]
I tried unchecking "Use custom application appearance" and restarted but same issue.

**Comment by MarshallOfSound** [comment]
It looks like an adobe flash issue.  Is your flash player up to date / installed at all

**Comment by dwasyluk** [comment]
I do have flash player installed - _You have version 20,0,0,286 installed_ via the Adobe website checker thing. It is the debug player, perhaps that is having an impact?

**Comment by dwasyluk** [comment]
I agree its flash related (without knowing anything about the code behind this)- right clicking the white square brings up the typical flash player context menu (zoom, about flash player, etc).

**Comment by MarshallOfSound** [comment]
*When in doubt turn it off and on again*

Try uninstalling flash and reinstalling.

**Comment by dwasyluk** [comment]
> When in doubt turn it off and on again

That worked! I uninstalled and reinstalled the same debug player, voila! Thanks for the suggestion :+1:
