### ISSUE TITLE
Block Explicit songs in radio

### ISSUE THREAD

**Issue by ryan8382** [radiant-player/radiant-player-mac#495]
I'm running 10.11.3. When I try to check those boxes I see an action but it doesn't check. I had someone else on theirs and same behavior. I do like the design.

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac - this appears to be another of those "broken in Safari" issues - the checkboxes don't appear to check

**Comment by chrismou** [comment]
@jacobwgillespie You literally beat me to the reply by seconds ;-)

**Comment by chrismou** [comment]
I'm not sure what the solution to this, short of pressing ahead with the electron version.  Google claim it's supported in all modern browsers, but that's clearly not the case.  There seems to be a load of really basic stuff broken in Safari, Firefox and IE.

Incidently @ryan8382, Radiant essentially uses Safari behind the scenes, so whenever something appears broken in Safari, it'll almost definitely be broken in Radiant too. There's a few outstanding issues related to this.

**Comment by chrismou** [comment]
I'm going to close this issue for now as it's essentially a Google bug.

Hopefully in the future we'll be able to move to a webkit based backend and this won't be an issue, but for now there's no real workaround.
