### ISSUE TITLE
Song search box when settings are open

### ISSUE THREAD

**Issue by ryan8382** [radiant-player/radiant-player-mac#496]
When you open the settings side bar the song the search box gets small. I would either slide the box over more to allow the search box text to still display or have the box slide over when the sidebar opens. Really like the product.

**Comment by jacobwgillespie** [comment]
Can you post a screenshot of what you're seeing?

**Comment by ryan8382** [comment]
There were a few more things that i saw. I marked them up also. 
![radiant_player_and_asian_exploration_-_noodles___company](https://cloud.githubusercontent.com/assets/10537547/12950303/23063e82-cfd2-11e5-884a-414cde3c2050.png)

**Comment by jacobwgillespie** [comment]
I see the search bar issue, though that's more on Google's end than Radiant's (since Radiant is just a wrapper for Google's web player).  There may be something we could do to adjust it though.

For the hamburger menu disappearing and the sidebar overlapping, that looks strange and isn't what I'm getting.  What version of Radiant and OSX are you using?

Here's what mine looks like:

![screenshot 2016-02-10 08 49 42](https://cloud.githubusercontent.com/assets/130874/12950547/51d2a8d0-cfd3-11e5-916d-6b47bd2d7941.png)

Does it still happen if you restart Radiant?

**Comment by ryan8382** [comment]
It may have something to do with moving the window between monitors. I have 3 external monitors connected to my MBP. I am also seeing issues that I can't move the windows back to a different monitor after i have moved it. Restarting the app and normal behavior restores. I am running 1.6.2. Just downloaded today from a friends recommendation.

I am running 10.11.3 and all updated. I have Chrome 48.0.2564.103 (64-bit) installed also.

**Comment by jacobwgillespie** [comment]
Interesting - @radiant-player/radiant-player-mac, any of you guys have external monitors you could use to test (I've just got the one iMac screen).

Yeah, you're up to date on OSX and Radiant.  Chrome actually doesn't affect things (Radiant uses a built in copy of the Safari engine that comes with OSX).

**Comment by chrismou** [comment]
I'm using 2 monitors plus the laptop screen at the office, though tbh I don't think I've ever dragged radiant across more than 2 of the screens.

Can test when I'm back. Though currently recovering from the flu, so doubt it'll be before next week.  I'll check it out then.

**Comment by shawn-mitch** [comment]
FWIW, I just tried this with my 3 monitor setup (2 external, MBP screen). Besides the window jumping bug, I didn't have any issues. The UI looks/works normally, and I can move the window back after moving it to another monitor. My guess is that it's not related to monitor setup.

**Comment by MarshallOfSound** [comment]
FWIW I tried it with my 3 monitor aswell (2 external and internal screen).  I don't even get the window jumping bug, looks perfectly fine to me.  If I had to guess could be to do with low resolution or high DPI scaling?

**Comment by jacobwgillespie** [comment]
This is likely fixed by 1.8.0 or wontfix, but feel free to post back if you experience any more issues or figure anything else out.
