### ISSUE TITLE
1.7.0 failing to update

### ISSUE THREAD

**Issue by jacobwgillespie** [radiant-player/radiant-player-mac#500]
Apparently the Sparkle updater checks to validate that the DSA keys in the old and new binaries match (not just the signatures) - this is preventing the 1.7.0 update from extracting.  I'm digging into ways to mitigate now.

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac - can I get your thoughts:

Would it be better to push a modified build as a 1.7.1 signed with the old DSA key that allowed updating without the DSA key match check, followed immediately by a new 1.7.2 release with the new DSA key and stock updater, or should we put a large message in the update release notes for 1.7.0 asking people to manually download from the website?

I'm leaning towards the later for now as it's more secure, though the former is slightly more streamlined for users.

**Comment by chrismou** [comment]
Asking people in the release notes to download/install manually is a bit grim.

How much work do you think this is going to be to fix? Or rather, do you know what's involved in fixing it?  If you think you'll have it licked tonight then the manual download thing isn't so bad as not many people will see it.  If you think this could stretch over several days, then I'm tempted to say go with the 1.7.1 release idea.

**Comment by jacobwgillespie** [comment]
Yeah, the downside is we'll have a release (1.7.1) that essentially bypasses security checks.  If we're okay with that, I'll get it out the door.

**Comment by chrismou** [comment]
Oh wait, isn't this just reverting it back to the old signing key?  So have we been bypassing security checks for a while, or is there more to it than that?

**Comment by jacobwgillespie** [comment]
Yep - so, we have 1.6.2 released in the wild (with a compromised DSA key).  We can't update to 1.7.0 (with the secure DSA key) as the keys don't match.

We can either force people to update manually, or we can create a 1.6.3 transitional release signed with the old DSA key that shortcuts the uploader so that it allows updates without checking DSA keys.  That release will be vulnerable to MITM attacks...

It's probably the best option though (especially since it'll just be a transitional release - i.e. people will update right after it's installed).  I'll see about coding it now.

**Comment by chrismou** [comment]
OK cool, I'll leave it up to you to make the call. It seems like you know what's involved, so whichever you think's best

**Comment by jacobwgillespie** [comment]
Okay, just pushed 1.6.3 - after it builds, I'll verify the upgrade path with my copy of 1.6.2, but it appears to work.

**Comment by jacobwgillespie** [comment]
Sweet, that worked!  :tada:  Hopefully we never have to do that again.  :smile:

**Comment by chrismou** [comment]
Worked for me :+1:  Good work, crisis averted! :smile:
