### ISSUE TITLE
Fonts Not Loading Correctly

### ISSUE THREAD

**Issue by JustinTBrown** [radiant-player/radiant-player-mac#505]
Typography does not seem to be loading correctly:

![screen shot 2016-02-20 at 12 33 46 pm](https://cloud.githubusercontent.com/assets/1620519/13198758/b0214312-d7ce-11e5-9d45-3d0af488c0b7.png)

I'm using v1.7.1 on OSX 10.10.5

**Comment by jacobwgillespie** [comment]
Does it do this if you load it up in Safari?  Also, is your system language set to english?

**Comment by JustinTBrown** [comment]
Sorry for delay. The issue is no longer happening actually. For future reference though: by "...load it up in Safari.." do you simply mean for me to point Safari to the Google Play url (play.google.com/music)?

**Comment by jacobwgillespie** [comment]
Cool, maybe it was a Google issue.  Yep, that's what I meant about Safari - Radiant is essentially just embedded-Safari with some niceties, so it's a good test to know if the issue is on Google's end or ours.

**Comment by JustinTBrown** [comment]
Sounds good. Many thanks :)
