### ISSUE TITLE
App Switcher (CMD+Tab): Radiant Player doesn't show up!? 

### ISSUE THREAD

**Issue by mili2110** [radiant-player/radiant-player-mac#508]
Hi guys, 
I got a couple issues...
1. When I am in another app and want jump back to Radiant, Radiant Player doesn't appear in the app switcher (cmd+tab)!?
2. there is no dot under the radiant icon in the dock when radiant player is open :/
3. The options menu is missing for me when i'm in radiant player, the shortcuts work though (cmd+ ,)
Someone got the same issues? I'm on Mac OS 10.11.4 Beta + latest flash player (v. 20) 
Thank you!

**Comment by chrismou** [comment]
Hi

I'm not seeing any of the issues you've listed.  That said, I'm on OSX 10.11.3. It's possible that these issues could be from the OSX beta, so it may be worth waiting until 10.11.4 and see if that fixes the issues for you.

Out of interest, did you see any of these problems on 10.11.3? Or did it just start since you installed the beta?

- Chris

**Comment by mili2110** [comment]
Hi Chris, 
I've been having these issues ever since I've started using radiant player over a year ago. Thats why I thought it must be an app issue... With 1.7.1 at least radiant player shows up in Exposé for me now.

**Comment by jacobwgillespie** [comment]
I'm on 10.11.3 as well and not experiencing the issue...  If you've been experiencing this for a while, what other software do you have installed?  (especially anything that might affect the dock, window management, or theming)

**Comment by mili2110** [comment]
Nothing extraordinary...
I used to use better touch tool for better windows management (split screen windows like windows 7), (https://www.boastr.net/) but have uninstalled it over a year ago since it came with os x 10.11(!?)...:/

**Comment by jacobwgillespie** [comment]
Is this still happening with the latest 1.8.0?

**Comment by mili2110** [comment]
yes, but I think it has to do with my os x installation...tested it on another Macbook Air and it works as its supposed to. I'll just do a re-install of Mac OS X....Thank you guys!

**Comment by chrismou** [comment]
Cheers for letting us know! :-)
