### ISSUE TITLE
Yosemite dark mode mini player 'next/previous song' color wrong

### ISSUE THREAD

**Issue by lynnard** [radiant-player/radiant-player-mac#510]
![screen shot 2016-03-05 at 15 59 40](https://cloud.githubusercontent.com/assets/1991754/13548576/4b30da9e-e2eb-11e5-8f93-0c1a857bc277.png)

**Comment by chrismou** [comment]
I feel a bit silly asking this, but - what preference are you using to get the dark style mini player?  I use the Dark Cyan theme pretty much exclusively, but I still have the default mini player.

**Comment by lynnard** [comment]
There is a setting inside System Preference -> General that can turn the entire Mac theme into Dark mode.

By the way, the problem I described seems to have disappeared, so I'm closing it.

**Comment by chrismou** [comment]
Ah-ha, so it's a system setting. Gotcha.

I have no idea why it fixed itself, but I'm claiming credit anyway. You're welcome :wink:
