### ISSUE TITLE
“Radiant Player” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by jamesb303** [radiant-player/radiant-player-mac#517]
I'm getting this error after downloading the app and clicking on it from my Downloads folder.

"“Radiant Player” can’t be opened because it is from an unidentified developer.
Your security preferences allow installation of only apps from the Mac App Store and identified developers.
Safari downloaded this file today at 4:55 PM from radiant-player.github.io."

I tried finding the app from the App Store but it is not there.

NOTE: I'm using a Mac on El Capitan OS 10.11.3 and wanted to use this instead of Safari 9.0.3.

**Comment by jacobwgillespie** [comment]
Yes, this is expected - we are not signing the app with an Apple developer identity and the app isn't available on the App Store.  To install, you will want to right-click on the application and pick Open.  Then, when it tells you that it is from an unidentified developer, it will give you an option to open anyways.  After you do that once, it will remember and not prompt you again.

**Comment by chrismou** [comment]
As an alternative to the app store, someone's kindly added Radiant to homebrew.  Assuming you use homebrew, you can install it by running:

`brew cask install radiant-player`
