### ISSUE TITLE
doesn't scrobble to last.fm reliably

### ISSUE THREAD

**Issue by matthewdias** [radiant-player/radiant-player-mac#518]
Seems to only be picking up like 5% of scrobbles.

**Comment by chrismou** [comment]
Last.fm were having some API issues last week that affected scrobbling - I was having the exact same issue: https://getsatisfaction.com/lastfm/topics/and-scrobbling-stopped-working-again

You should be able to fix this by deauthorizing the player, then reauthorizing (Preferences > Last.fm > Deauthorize).  You may need to restart the player in between those steps.

Let me know if you're still having issues.
