### ISSUE TITLE
Explicit Album Icon Z-index is higher than search results dropdown

### ISSUE THREAD

**Issue by Rrivera5127** [radiant-player/radiant-player-mac#519]
if you have an album with the explicit content icon underneath the search results dropdown you will see the "E" icon above the search results

Example:
http://imgur.com/RRd4LkG

**Comment by jacobwgillespie** [comment]
Can you check this on Safari? (i.e. open https://play.google.com/music/listen in Safari and see if it does the same thing)

**Comment by Rrivera5127** [comment]
tested Safari 9.0.2 on the same computer and the explicit icon is rendered below the search results.

**Comment by chrismou** [comment]
Interestingly, the only place we manually set a z-index is in a stylesheet we don't use anymore, so I'm not sure what could be affecting it offhand.

Anyways, fixing this may just be as simple as setting a higher z-index for the `<sj-search-box>` tag. Will need to test it across all the themes.

**Comment by Rrivera5127** [comment]
This issue seems to be fixed now, i don't know what changed (i didn't touch anything).

**Comment by chrismou** [comment]
Hmm, I've not touched it either. And I was definitely seeing the same issue as you.

Put it down to a Google style tweak I guess?  :-/
