### ISSUE TITLE
Holding down space causes repeated play/pause

### ISSUE THREAD

**Issue by apramana** [radiant-player/radiant-player-mac#522]
It would be more beneficial to only trigger play/pause when the key is released.

**Comment by jacobwgillespie** [comment]
This behavior is coming from Google's end of things (you can see the same behavior happening in Chrome or Safari).  You may want to send this suggestion to them as feedback - to do so, click the menu icon at the top left, choose Help and Feedback from the menu, then choose Send Feedback (it'll be at the bottom of the help dialog).
