### ISSUE TITLE
Won't work without Flash. Make an HTML5 version.

### ISSUE THREAD

**Issue by gravyplaya** [radiant-player/radiant-player-mac#525]
Please make a version that uses HTML5 and NOT FLASH.. Flash is no longer supported on Mac systems. New machine and I dont want to install flash just to use this app.

**Comment by chrismou** [comment]
Radiant Player uses Safari in the background to render, and unfortunately Google Music doesn't yet support HTML5 on Safari.

**Comment by gravyplaya** [comment]
It does if you select HTML5 in the music player preferences.

**Comment by chrismou** [comment]
It's greyed out - it won't let me enable it. I'm not sure if Google just hasn't enabled it for Safari, or if Safari just doesn't yet support it.  I think it's the latter.

<img width="1264" alt="screenshot 2016-03-25 19 41 07" src="https://cloud.githubusercontent.com/assets/319883/14052368/a7871160-f2c1-11e5-810c-699d13aa0b2e.png">

**Comment by chrismou** [comment]
If you're able to enable it, could you send me a screenshot of your settings page with it enabled and let me know what version of Safari and OSX you're running?
