### ISSUE TITLE
Controls not showing up and some UI issues

### ISSUE THREAD

**Issue by ianoroceo** [radiant-player/radiant-player-mac#530]
Radiant Player Version: 1.7.4
OS Version: Mac OS X Yosemite 10.10.5

Please see screenshot below.
Issues
1. Controls are not showing up on the bottom
2. Headers (Search and accounts icon/controls)
3. Recent Activity Tiles are overlapping over the See All button for Recent Activity

![fullscreen_3_29_16__8_48_am](https://cloud.githubusercontent.com/assets/15149237/14114239/1cf9eb90-f58b-11e5-88d4-afd7b2ef8fe6.jpg)

**Comment by antwonw** [comment]
Having the same issue on 1.7.4 running on OS X 10.10.5.

**Comment by jjstickel** [comment]
Same here. Also OS X 10.10.5.

**Comment by jacobwgillespie** [comment]
Duplicate of #523 - we have a fix staged in PR #529 that should go out sometime today.
