### ISSUE TITLE
Searchbox not working

### ISSUE THREAD

**Issue by nicoloverardo** [radiant-player/radiant-player-mac#531]
The searchbox doesn't work in any page except for "My Library" page.
When i start typing and the instant search gives me results, also I cannot type in it anymore unless by going back to my library

I'm using El Capitan 10.11.4 and Radiant 1.7.5

**Comment by jacobwgillespie** [comment]
Odd, I'm not able to reproduce on my machine - can you see if it behaves the same way in Safari?  And if not, try restarting Radiant / restarting your computer, etc. to verify that it's not a temporary thing.

**Comment by nicoloverardo** [comment]
Cleaned temp, restarted, logged-out and logged-in again, even uninstalled and reinstalled the app. Still not working, and in Safari it works as it should.
I've uploaded two pictures here if they can help you. Let me know if you need some logs or anything.
![1](https://cloud.githubusercontent.com/assets/6330371/14143813/69487e5a-f68d-11e5-84a1-635be7356139.jpg)
![2](https://cloud.githubusercontent.com/assets/6330371/14143814/694d9d68-f68d-11e5-84df-491295d18b6b.jpg)

**Comment by leemm** [comment]
I've got the exact same issue since verion 1.8.0.  What's changed to do with it?
El Capitan here.

**Comment by nicoloverardo** [comment]
Updated to v1.8.0 and also updated Flash to 21.0.0.197.
Issue still present unfortunately.

**Comment by jacobwgillespie** [comment]
I can't seem to reproduce - do you guys have any more info on your environment?  Do you have the custom title bar appearance option enabled, or the custom style option?  Any other software installed that could have anything to do with this?  @nicoloverardo, you're on an internationalized version of GPM, @leemm are you as well or are you on the US version?

**Comment by BarakaAka1Only** [comment]
I've downloaded and installed El Capitan and it works perfectly fine for me on all styles, with and without custom title bar enabled. When looking at the style element via #material-one-middle it does have position:relative; associated with it if i put a z-index: -1 on it, it reproduces your guys' exact issue so i wonder if we were to apply a bigger z-index would it fix it?

I went ahead and applied a test version following:


`- (BOOL)isElCapitan`
`{`
   `return floor(NSAppKitVersionNumber) <= NSAppKitVersionNumber10_10_Max ? 0 : true;`
`}`

which emulates : 

` if (floor(NSAppKitVersionNumber) <= NSAppKitVersionNumber10_10_Max) {`
` } else {`
`     return true;`
`  }`

from https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/ ( as NSAppKitVersionNumber10_11 doesn't exist)

applying:

`if ([self isElCapitan]) {`
`        [self applyCSSFile:@"zindex"];`
` }`

containing just a zindex.css file in the css folder with:

`/* z-index fix for El Capitan */`

`#material-one-middle {`
`    z-index: 999;`
`} `

it can be downloaded here:
https://www.dropbox.com/s/up0ibgk8hs7knxo/El%20Capitan%20Radiant%20Player.app.zip?dl=0

Hopefully this is the case if not then i am not sure but worth a shot...

**Comment by bouss1** [comment]
I have the same problem on El capitan with versions above 1.75. Returned to 1.74 which works fine.

**Comment by BarakaAka1Only** [comment]
Did my test version i've attached work at all for you @bouss1?

**Comment by Grsmto** [comment]
I have the same issue and I confirm that adding a `z-index: 1` on `#material-one-middle` fix the issue.
Btw @BarakaAka1Only better avoiding set unnecessary high z-index value (to avoid side-effects).
I checked between Safari/Radiant and I don't see any difference...I don't get why it works on Safari and not on Radiant.

**Comment by BarakaAka1Only** [comment]
@Grsmto i understand that, i only applied a high value to see what would happen, if z-index: 1 is working fine then i suppose from my adding 999 should be reverted to just one then ;)

**Comment by leemm** [comment]
I can confirm that @BarakaAka1Only test app works fine on both my Macs running El Capitan.  Good stuff :)
