### ISSUE TITLE
Music controls not showing up on OS X Mavericks

### ISSUE THREAD

**Issue by Zantinga** [radiant-player/radiant-player-mac#532]
Version 1.7.5 on OS X 10.9.5 is not showing the music controls (pause, audio level, next song, etc).
![screen shot 2016-03-30 at 10 21 48 am](https://cloud.githubusercontent.com/assets/6440317/14145293/50edf6a4-f661-11e5-9bdb-23baf0075245.png)

**Comment by erikretz** [comment]
Same Issue here, with the lastest player 1.8  (but happened with the last 2 or 3 versions also.)  OSX 10.9.2

![screenshot 2016-03-30 16 52 02](https://cloud.githubusercontent.com/assets/6945210/14160154/cf41ab00-f697-11e5-8bdb-237727a73ed5.png)

**Comment by jacobwgillespie** [comment]
Can you guys redownload a copy of 1.7.4 from https://github.com/radiant-player/radiant-player-mac/releases/tag/v1.7.4 and let me know if it's happening there?

**Comment by Zantinga** [comment]
Tried 1.7.4 and it's having the same problem too...
![screen shot 2016-03-31 at 9 35 50 am](https://cloud.githubusercontent.com/assets/6440317/14177382/0fae3884-f724-11e5-9810-a704d78699ed.png)

**Comment by chrismou** [comment]
Hey @Zantinga - 1.8.0 is out with a potential fix. Could you give it a go and let us know how it goes?

I'm not 100% if it will seeing as you're on Mavericks, but it's worth a go.

**Comment by Zantinga** [comment]
@chrismou Still no luck with 1.8.0. That's the version that the bug started on, and downgrading didn't seem to fix it.

**Comment by BarakaAka1Only** [comment]
gonna see what i can do to help looks like this is another css issue, i already fixed the issue with Yosemite (as it had the same exact issue), i'll see if i can get a copy of OS X 10.9.5 running and debug from there.

**Comment by BarakaAka1Only** [comment]
Okay got a hold of OS X 10.9.5 and upon debugging, it had the same issues as Yosemite had via the flex support was getting ignored. The only difference with Mavericks and Yosemite from my fix is that Mavericks had a hover issue with the volume slider not showing up. I went ahead and adjusted that so @jacobwgillespie with my fix it will also has to apply to 10.10.5 and below as from looking at radiant's source code it only includes the flexfix.css 

`if ([self isYosemite]) {`
`[self applyCSSFile:@"flexfix"];`
`}`

Not sure if that was meant to be like that but anyhow here is the updated css fix for the flex issues:

https://www.dropbox.com/s/vvh192ybi0o54cb/google-baraka-flexonly%5Bupdated%5D.css?dl=0

<img src="http://i.imgur.com/OeNU7Rt.jpg"/>

<img src="http://i.imgur.com/iIev4xn.jpg"/>

**Comment by BarakaAka1Only** [comment]
Here is a test version just for testing:

https://www.dropbox.com/s/qwe9yuqmuqr7fjt/Mavericks%20Radiant%20Player.app.zip?dl=0

added just a minor change to detect if on Mavericks ( not sure if this is right way to do it but i tested it and works :| )

`if ([self isYosemite] || [self isMavericks]) {`
`      [self applyCSSFile:@"flexfix"];`
`}`
`- (BOOL)isMavericks`
`{`
`    return floor(NSAppKitVersionNumber) > NSAppKitVersionNumber10_8;`
`}`

**Comment by erikretz** [comment]
This test version fixed my problems on OSX 10.9.2

-Erik

[image: Inline image 1]

**Comment by BarakaAka1Only** [comment]
@erikretz Awesome :D

**Comment by jacobwgillespie** [comment]
Thanks, @BarakaAka1Only - submitted this as PR #534.

**Comment by jacobwgillespie** [comment]
This is building now and should go out as v1.8.1

**Comment by BarakaAka1Only** [comment]
Awesome :)
