### ISSUE TITLE
Playback control from BT headphones

### ISSUE THREAD

**Issue by CarlosRDomin** [radiant-player/radiant-player-mac#545]
I really like being able to control Radiant Player from the keyboard (Play/Pause, Previous song, Next song). Unfortunately, I haven't been able to do so from my bluetooth headphones (EP650), which also have Play/Pause, Next and Previous buttons.
I wonder if other users have noticed the same behaviour with different bluetooth headsets and, if so, whether this functionality could be added to future versions of Radiant Player.
Anyway, great job man!! 👍

**Comment by jacobwgillespie** [comment]
Yeah, the (previously) poorly-named #466 refers to this.  I renamed it, and I'll close this issue as a duplicate.  Thanks!

**Comment by CarlosRDomin** [comment]
Yup,  #466 looks like a duplicate of my issue, my bad I missed it with the old title. Thanks for taking care of it so quickly!
I may have some free time next week so if I figure out a fix before you guys do I'll work on a pull request :)

**Comment by BobHatcher** [comment]
It took me a while to get Radiant Player to respect the Forward/Back/Play/Pause buttons on my bluetooth headphones, so I'll leave this here for the benefit of anyone who may find this by way of their trusty Google machine.

on Sierra 10.12.2 (16C67)

1. Use this tool: http://thebitguru.com/projects/itunes-patch to disconnect iTunes from the default buttons. On Sierra, I needed to do the additional step of booting into recovery mode to use `csrutil`. 

2. This tool: https://github.com/jguice/mac-bt-headset-fix is a small app called bubo that maps the Bluetooth buttons to the function buttons.

Using these two things, the Bluetooth buttons on my Plantronics Backbeat Pro 2 headphones work flawlessly with Radiant Player.

**Comment by CarlosRDomin** [comment]
@BobHatcher that's awesome, thanks for sharing the finding! Wonder if we should integrate the mac-bt-headset-fix functionlity into RadiantPlayer, or at least leave the link in the Readme/description so people can download it if interested :)
Anyway, thanks!!
