### ISSUE TITLE
How do you clear the preferences

### ISSUE THREAD

**Issue by olayinkasf** [radiant-player/radiant-player-mac#546]
I tweaked the preferences and now the menu bar doesn't show anymore. How do you clear or reset the preferences.

**Comment by tjanson** [comment]
The preference file is at `~/Library/Preferences/com.sajidanwar.Radiant-Player.plist`.

**Comment by jacobwgillespie** [comment]
Closing this issue as I believe it has been resolved - feel free to post back if that's not the case.
