### ISSUE TITLE
Can't login to last.fm and also media keys no longer work

### ISSUE THREAD

**Issue by japhex** [radiant-player/radiant-player-mac#547]
I noticed tracks weren't scrobbling so I deauthorized to try and re-authorise and fix the issue, now I can't authorize with last.fm at all - it logged in on the actual site with the same details successfully.

Also, the play/pause/forwards/backwards media keys on my keyboard no longer work with Radiant Player at all? Any ideas dudes? 

v1.8.3

**Comment by tjanson** [comment]
The media keys sound like #550. Perhaps you can add a comment there to describe when the issue occurs (always?). (Unfortunately it doesn’t look like anyone’s figured out the cause yet.)

You could then remove the media key problem from this issue, assuming the Last.fm problem is still current.

**Comment by japhex** [comment]
I'm using v 1.8.4 and all seems to be fine now! :)
