### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by affert** [radiant-player/radiant-player-mac#551]
<img width="569" alt="screen shot 2016-04-26 at 8 05 54 am" src="https://cloud.githubusercontent.com/assets/424202/14819003/b9567192-0b85-11e6-8971-f1acb114a3ce.png">
When I start Radiant Player, all I get is the following message: "An SSL error has occurred and a secure connection to the server cannot be made."   According to the update option, I'm up to date on version 1.8.3

**Comment by jacobwgillespie** [comment]
Do you experience any errors opening GPM in Safari?

Can you right-click the page, choose Inspect, switch to the Console tab in the web inspector, and screenshot the contents?

And are you on any abnormal network environments (corporate network, public wifi, etc.)?

**Comment by affert** [comment]
Ah, it also fails to load from my browser.  I tracked it down to a network setting.  (the site was being blocked by my opendns settings)

It's working again! :)

**Comment by jacobwgillespie** [comment]
Sweet, glad it's working!

**Comment by PhilAtTelesisHQ** [comment]
I had the same problem.  It was caused by the Kaspersky Internet Security suite (on Mac).  I had to change the Protection > Web Anti-virus > Check Secure Connections setting to "Only for parental control."  That did it.  I'm not sure how to simply exclude the app from this protection.
