### ISSUE TITLE
Add 'I'm Feeling Lucky' button to mini player.

### ISSUE THREAD

**Issue by blefevre** [radiant-player/radiant-player-mac#560]
The official Google Mini Player has an I'm Feeling Lucky button above the music controls.

I use this all them time to change up what I'm listening to.

![screen shot 2016-06-23 at 3 45 25 pm](https://cloud.githubusercontent.com/assets/7812906/16317573/c4ff8af4-3959-11e6-9ed3-842715ea97c5.png)

It'd be nice to see this added to the Radiant Mini Player.

**Comment by BarakaAka1Only** [comment]
I went ahead and added this check out the pull request https://github.com/radiant-player/radiant-player-mac/issues/581

**Comment by jacobwgillespie** [comment]
This has been added in v1.10.0 🎉
