### ISSUE TITLE
App blocked due to non-identified developer

### ISSUE THREAD

**Issue by lemonzi** [radiant-player/radiant-player-mac#565]
We are only allowed to run apps from "identified developers" at my workplace; I'm not sure what are the requirements to qualify as such, but any chance someone has clearance and is willing to sign the build?

**Comment by jacobwgillespie** [comment]
So, the right-click-the-app, then click open, then click run trick is blocked as well?

I'm hoping to sign the next version of Radiant (2.0) that is essentially a rewrite - it's not quite ready yet though, and I haven't gotten around to setting up the signing.

**Comment by lemonzi** [comment]
Oh! This worked, thank you so much! I tried going to the security preferences, where it picked that I had tried to open it, clicked on some button to open it anyway, and it didn't work.

**Comment by jacobwgillespie** [comment]
Nice 👍
