### ISSUE TITLE
⌘F doesn't focus on search bar

### ISSUE THREAD

**Issue by chamini2** [radiant-player/radiant-player-mac#567]

**Comment by jacobwgillespie** [comment]
This probably won't fix, but just to be sure, can you close and re-open Radiant and verify it's still broken?

If it still doesn't work, what version of OSX are you using?

**Comment by chamini2** [comment]
Closed and re-opened and it's still broken.

I'm using MacBook Pro (Retina, 15-inch, Mid 2014) 10.10.5
