### ISSUE TITLE
Offline radio

### ISSUE THREAD

**Issue by knservis** [radiant-player/radiant-player-mac#571]
Hi, 

I am on a very unreliable network where it would be very useful to be able to download a radio (as I can do on my android client) for offline listening. Hard as I tried, I could not find that option on radiant. Did I miss it or is it missing? In the latter case it would make a great addition to the player. 

Thank you

**Comment by jacobwgillespie** [comment]
Is this possible on the Google Play Music website?  We are a native wrapper around that, so if there's a way to do it from the website, it might be possible inside Radiant.

**Comment by jacobwgillespie** [comment]
I'm going to close this as I do not believe it's an option we are able to support (since the Google Play Music website does not).
