### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by kidpollo** [radiant-player/radiant-player-mac#577]
Did Radiant Player stopped working for anyone else?

I tried reloading every which way. Feels to me like google implemented something to block it.
![radiant_player](https://cloud.githubusercontent.com/assets/8182/17349730/07dcc9a0-58d5-11e6-81f1-1ba2a10bf155.png)

**Comment by dstockto** [comment]
Yeah, it's done line dinner for me too.

`ReferenceError: Can't find variable: gmusic` (along with a lot of other errors)

**Comment by davepagurek** [comment]
Does this fix it? https://github.com/radiant-player/radiant-player-mac/pull/578

**Comment by kidpollo** [comment]
@davepagurek how do I test?

**Comment by davepagurek** [comment]
You can clone my branch, open `radiant-player-mac.xcworkspace`, and run from there and see if you still get a grey screen and the same errors in the console

**Comment by dstockto** [comment]
The app in the zip works for me.

**Comment by dstockto** [comment]
And the code in your branch works for me as well @davepagurek.

**Comment by mike3run** [comment]
Can confirm, app broken but zip file fixes it 👍

**Comment by jacobwgillespie** [comment]
Fixed in #578

**Comment by jacobwgillespie** [comment]
And released as 1.9.0
