### ISSUE TITLE
Blank Screen on Launch

### ISSUE THREAD

**Issue by jace74** [radiant-player/radiant-player-mac#579]
HI,

When launching the app i get nothing but a blank window (screen shot attached).  It has always worked fine previously an I cannot think of anything that has changed.  I'm running version 1.8.5 of Radiant on OSX 10.11.6
![screen shot 2016-08-03 at 12 49 59 pm](https://cloud.githubusercontent.com/assets/20807153/17352354/57ce3c38-5979-11e6-8d40-d68a7766e5dd.png)

**Comment by jacobwgillespie** [comment]
This should be fixed in 1.9.0 (released a few minutes ago)
