### ISSUE TITLE
"Music Library" is "undefined" on the sidebar

### ISSUE THREAD

**Issue by ryofurue** [radiant-player/radiant-player-mac#586]
Hi,  Thank you for the useful, cool player.

After a recent update, "Music Library" is displayed as "undefined" on the menu bar on the left hand side.  The top five items now reads

    Listen Now
    Top charts
    New releases
    undefined
    Browse stations

Clicking on "undefined" takes you to "Music Library".  So, functionally, it's fine.  (By the way, it would look better if all items are capitalized, such as "Top Charts", "New Releases".)

Radiant Player Version 1.10.0 .

Hope this helps,

Ryo

**Comment by chrismou** [comment]
This also looks to be present on the previous version, and GPDMP. Looks like a change at Google's end (heads up @MarshallOfSound)

**Comment by chrismou** [comment]
Quick glance at listen_extended.js - now we just need to work out what `(p ? N(me) : N(Iea.MCb)) + mb` relates to 😂

**Comment by MarshallOfSound** [comment]
Yeah, I've been getting reports of this for days.  It's a Google issue, I tried to hack around it but then couldn't be bothered fixing googles mistakes 👍

**Comment by jacobwgillespie** [comment]
@chrismou do you have a console error screenshot / log for that?  You international users are getting updates first.  :)

**Comment by chrismou** [comment]
Ah, I did notice the en_gb at the end of the filename. Sometimes forget I'm considered "international" 😂

There were no errors in console, but will post everything I see in a bit when I'm back in the office!

**Comment by chrismou** [comment]
This looks to have been fixed at Google's end at some point in the last 24 hours

![screenshot 2016-08-17 09 29 34](https://cloud.githubusercontent.com/assets/319883/17729653/22a10de4-645d-11e6-8a98-11ea89b3a3ae.png)
