### ISSUE TITLE
Minor cosmetic suggestion: Move "Feeling Lucky" mini-player button

### ISSUE THREAD

**Issue by tjanson** [radiant-player/radiant-player-mac#587]
The "I’m feeling lucky" button added in #560 appears in a new row in the mini-player:
![screen shot 2016-08-15 at 21 43 19](https://cloud.githubusercontent.com/assets/532114/17677127/af8395ec-6331-11e6-942d-240ca5735627.png)

This may be a question of taste, but I think the icon would feel right at home (visually and semantically) in the row of playback controls, like this:
![screen shot 2016-08-15 at 21 43 19 copy](https://cloud.githubusercontent.com/assets/532114/17677345/af608ea2-6332-11e6-978b-20d24f499349.png)

Or, while we’re at it, maybe like this?
![screen shot 2016-08-15 at 21 43 19 copy 2](https://cloud.githubusercontent.com/assets/532114/17677510/5a13df98-6333-11e6-90d5-c8c3f0491438.png)

**Comment by BarakaAka1Only** [comment]
Well if more users agree for that change i'll be more than happy to adjust it or someone in the team. Moreless it's not bad idea per-say just like you said, "question of taste" ;)

**Comment by chrismou** [comment]
tbh I do prefer how it looks aligned with the other buttons. Takes up a lot less space

How much work would it be to shuffle it down to the bottom?  If you're up for taking a look, I'd say go for the first screenshot, so the existing buttons remain consistent with how they're positioned in the main player.

**Comment by BarakaAka1Only** [comment]
@chrismou It's actually pretty simple once you get the hang of it :P But yeah i'm up for taking a look since i'm the one whom added it haha, i'll put a example link for testing here shortly.

**Comment by BarakaAka1Only** [comment]
Okay here it is :)

**Screenshots:** 

![image](https://cloud.githubusercontent.com/assets/2947494/17694293/ca4d24a6-6368-11e6-896b-e58ae9b5f614.png)

![image](https://cloud.githubusercontent.com/assets/2947494/17694316/dfa6d81a-6368-11e6-9988-b6fe6c23dd92.png)

![image](https://cloud.githubusercontent.com/assets/2947494/17694325/ebe32052-6368-11e6-8580-16bbe6c1847a.png)

![image](https://cloud.githubusercontent.com/assets/2947494/17694330/f32b3e8a-6368-11e6-980d-dfbb1378ebb5.png)

![image](https://cloud.githubusercontent.com/assets/2947494/17694338/fce8db3a-6368-11e6-905a-ff6545dcd015.png)

**Download:** (for testing)

https://www.dropbox.com/s/p4aq0ln4ior8756/I%27m%20Feeling%20Lucky%20v2%20Radiant%20Player.app.zip?dl=0

**Comment by jacobwgillespie** [comment]
Yeah, I think I prefer it on one line visually.  It does move the play/pause button out of the center, but it visually looks cleaner IMO.

**Comment by chrismou** [comment]
I much prefer it that way. Good shout @tjanson and good work @BarakaAka1Only for implementing it so quickly 👍 

I'll download the file this evening and test it properly. Feel free to PR in the meantime and I'll merge it in once it's tested :-)

**Comment by BarakaAka1Only** [comment]
@chrismou no problem and PR has been submitted 👍

**Comment by chrismou** [comment]
Changes applied in #588
