### ISSUE TITLE
Invalid listener argument / won't load (stops at around 98%)

### ISSUE THREAD

**Issue by squareclouds** [radiant-player/radiant-player-mac#589]
osx 10.11.6
avast 11.16
radiant player 1.10.1

tried uninstalling, reinstalling, clearing cache, reloading, deleting cookies. someone having the same problem? it started 2-3 days ago.

![bildschirmfoto 2016-08-19 um 10 37 32](https://cloud.githubusercontent.com/assets/9073054/17803808/f870ca58-65f8-11e6-9cdf-3a9b10776d34.png)

**Comment by ansgarhoffmann** [comment]
Same at me.
OSX 10.10.5
Radiant Player 1.9.0 - 1.10.1 - doesn't work anymore.

**Comment by jacobwgillespie** [comment]
If you right-click inside the app, choose Inspect Element, and click on the Console tab, are there errors?  Can you post them here?

**Comment by squareclouds** [comment]
sure. sadly icant really post everything, since it keeps throwing the same error (the error counter keeps counting up on screenshot).

[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js:11:21403)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Fa (conversion.js:20:113)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Fa (conversion.js:20:259)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Fa (conversion.js:20:406)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	Hya (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:916:83)
	(anonymous function)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: a.handleEvent is not a function. (In 'a.handleEvent(b)', 'a.handleEvent' is undefined)
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: a.handleEvent is not a function. (In 'a.handleEvent(b)', 'a.handleEvent' is undefined)
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	Hya (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:916:83)
	(anonymous function)
[Error] CustomError: Error in protected function: a.handleEvent is not a function. (In 'a.handleEvent(b)', 'a.handleEvent' is undefined)
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
	loaded
	contentLoaded
	(anonymous function)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
> Selected Element
< <div id="loading-progress">…</div> = $1
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
[Error] CustomError: Error in protected function: a.handleEvent is not a function. (In 'a.handleEvent(b)', 'a.handleEvent' is undefined)
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:141)
	appendChild
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:4350:318)
	(anonymous function)
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:132)
[Error] CustomError: Error in protected function: Invalid listener argument
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)

![bildschirmfoto 2016-08-19 um 14 46 58](https://cloud.githubusercontent.com/assets/9073054/17810176/e01eeb06-661b-11e6-9fda-83ba8ec4a5c2.png)

**Comment by apfelbox** [comment]
It is always the same error:

```
[Error] CustomError: Error in protected function: Invalid listener argument
c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__de.js:925:359)
```

**Comment by ansgarhoffmann** [comment]
The error exists at the new version 1.10.2 also.

![bildschirmfoto 2016-08-19 um 23 35 18](https://cloud.githubusercontent.com/assets/21121690/17825022/a3c7d114-6665-11e6-8fb4-b8669983e7ac.png)

**Comment by chrismou** [comment]
Can you guys try opening Google music in safari on your Sierra build and see if you're getting the same error? Interested to know if it's a change in safari that's causing this

**Comment by ansgarhoffmann** [comment]
There's no such errors in Safari Version 9.1.2 (10601.7.7)
Google Music is working fine there. :-(

![bildschirmfoto 2016-08-19 um 23 45 19](https://cloud.githubusercontent.com/assets/21121690/17825231/176e7edc-6667-11e6-8cee-dad128b1c2dc.png)

**Comment by iMoshi** [comment]
Same here, same exact error.

**Comment by chrismou** [comment]
So it works in Safari, but not in Radiant - which uses Safari under the hood. I think we need to get hold of a copy Sierra...

**Comment by squareclouds** [comment]
i can confirm that version 1.10.2 isnt working either.  @chrismou, i didnt understand your Sierra comment, could u please elaborate?

i had actually a couple of errors, and after that the one that kept going. 

> [Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.

i tested a few hours ago and my g-play was working in safari, firefox and chrome (el capitan)

**Comment by iMoshi** [comment]
Guys, use Safari's cookies in RP settings under Privacy tab.

It's ok, I already apologized to the devs for us being so dumb :P

**Comment by squareclouds** [comment]
why dumb? i changed the setting two days ago in 1.10.1 and it didnt work, just changed it in 1.10.2 and still doenst work. and if it was the case it shouldn't be an option to turn it off in the settings ^^ after the change not even the load screen loads

![bildschirmfoto 2016-08-20 um 09 54 09](https://cloud.githubusercontent.com/assets/9073054/17829861/14965cde-66bc-11e6-8d56-6d218dfe33d2.png)

**Comment by ansgarhoffmann** [comment]
The use of the "Safari cookie"-setting in RP does not change anything at me. It doesn't work ... same errors ...

**Comment by jacobwgillespie** [comment]
Yeah, not dumb, that's not usually a required option.  @iMoshi you have a different issue than the others on this thread (you have a `400 (Bad SID)` error), which seems to be an issue with Google sessions, hence why using Safari's cookies and session is working.

Still digging into this `Invalid listener argument` error...

**Comment by squareclouds** [comment]
i hope you can solve it soon, i need ma musiiiic :D and kinda got dependent of radiant...

**Comment by Fenix-Mueneren** [comment]
Use safari cookie doesn't seem to be working for me :(
And as long as the app is running, the Invalid Listener Arguments keep piling up, it only takes a couple of seconds for them to mount up to the thousands. T_T

**Comment by jacobwgillespie** [comment]
It looks like Google still hasn't rolled out this update here in the US, so I'm going to do some "blind" debugging.  Here are a series of modified app downloads for testing - let me know if any of these work for you:

* `001` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/001.zip - All Radiant JS disabled
* `002` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/002.zip (DOM-altering JS disabled)
* `003` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/003.zip (`002` + disabling I'm Feeling Lucky integration)
* `004` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/004.zip (all JS enabled, but all custom styles disabled)

I'd appreciate it if anybody experiencing this issue can let me know which of these work and which don't.  Unfortunately I don't think I'll be able to fix it just from these four tests, but it should hopefully point to which area is causing the troubles.

**Comment by ansgarhoffmann** [comment]
So, thanks.
My review:
001: App is starting, but without the play-buttons on the bottom. I can browse and play some by clicking on it, but there's no cover and no play, next, back-buttons ...
002: Works fine, so far
003: like 002, works fine
004: Doesn't work at all
So, it seems to me disabling DOM-altering JS would be the solution.

**Comment by katosan** [comment]
**002 & 003** working fine so far 
**001** behaves somewhat erratic and produces errors `https://r5---sn-1gi7znel.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id=8ccd0508c698e0e1&itag=25&source=skyjam&upn=aKGSqqUdMOA&o=05830953330874919167&range=1196407-2398040&segment=5&ratebypass=yes&ip=62.192.15.28&ipbits=0&expire=1472046501&sparams=expire%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Co%2Cpl%2Crange%2Cratebypass%2Csegment%2Csource%2Cupn&signature=0591593F7AC748377D96725B910077C99AEF920D.6B64D86EF07ABC8CF96E71CF26313D893E2BEC57&key=cms1&mm=31&mn=sn-1gi7znel&ms=au&mt=1472045812&mv=m&pl=23&cpn=6BNpsopbsgzVK1N6Failed to load resource: Plug-in cancelled`
**004** does not start at all

**Comment by jacobwgillespie** [comment]
Thanks for the info, that helps.  Here's some more builds with various things changed:

* `005` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/005.zip - back/forward buttons disabled
* `006` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/006.zip - entire navigation changes disabled
* `007` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/007.zip - `006` + draggable app bar disabled
* `008` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/008.zip - all JS enabled except for "main"
* `009` - https://dl.dropboxusercontent.com/u/6278910/RadiantTest/009.zip - all JS disabled except for gmusic.js

**Comment by katosan** [comment]
- 005: no boot
- 006: works but plugin error like above
- 007: works no error
- 008: no boot
- 009: works but plugin error like above

**Comment by squareclouds** [comment]
i can confirm that 007 works, i have a couple of errors thou

<img width="1280" alt="bildschirmfoto 2016-08-29 um 11 02 39" src="https://cloud.githubusercontent.com/assets/9073054/18046429/2b035fbc-6dd8-11e6-8cab-424b12bd7d83.png">

**Comment by tjkirch** [comment]
There's an easy fix from BarakaAka1Only on #600 that worked for me on Mac OS 10.10.5 -- you just make a small modification to navigation.js in the app bundle.

**Comment by jacobwgillespie** [comment]
Can you check with v1.10.3?

**Comment by atopuzov** [comment]
Works for me with 1.10.3.

**Comment by squareclouds** [comment]
working for me now as well, i think this can be closed
