### ISSUE TITLE
Error Loading Library - 400 (Bad SID)

### ISSUE THREAD

**Issue by iMoshi** [radiant-player/radiant-player-mac#591]
It's happening on the latest build. How do I allow this "unsafe header"?

![screen shot 2016-08-20 at 6 56 33 am](https://cloud.githubusercontent.com/assets/925613/17825410/575a0fde-66a3-11e6-983e-3b4146209daf.png)

**Comment by jacobwgillespie** [comment]
The unsafe header error has been around for a while for everybody so I don't think that's causing it, however the 400 Bad SID error is new.

Do you happen to run any antivirus (like perhaps Kapersky)?  I know similar issues have been reported with antivirus blocking certain Google services...

**Comment by iMoshi** [comment]
Not at all, no anti-virus has ever been installed. 

Well I have AdBlock installed both on Safari and Chrome and I first white-listed doubleclick.net but no go, then I disabled AdBlock and beautiful Radiant Player still refused to work. 

I've just read that Safari is under its engine and I went into its settings to disable "Fraudulent website" thing and fired up RP, still no go...

**Comment by jacobwgillespie** [comment]
Just to be safe, can you sign out of Google and back in inside Radiant?

**Comment by iMoshi** [comment]
Yup, tried it several times :) 

I've uninstalled the app using an app cleaner (which deletes all its hidden files and everything), installed a brand new RP with no cookies and nothing and still... 

Maybe it's Google blocking the app... You've got their attention :P

**Comment by jacobwgillespie** [comment]
Darn, so no easy fix.  I'll keep looking on my end, and you may actually want to report that 400 Bad SID error to Google via their help/feedback system.  Searching online shows that error popping up for various Google services.

**Comment by iMoshi** [comment]
Oh my god, I feel so stupid. 

Here's what we're missing. 

Settings in RP -> Privacy -> Use Safari cookies. Wow, do I feel stupid.. We're so sorry for being dumb :P 

![screen shot 2016-08-20 at 7 51 38 am](https://cloud.githubusercontent.com/assets/925613/17826367/f3a95ee2-66aa-11e6-9a83-992f66f88a15.png)

**Comment by gunnarbeutner** [comment]
I've been experiencing the same problem for the past couple of days. One of the major differences seems to be that I'm not getting any 400 errors:

<img width="1280" alt="radiant1" src="https://cloud.githubusercontent.com/assets/388571/17828962/fec05ac6-669e-11e6-9975-a139cacf882c.png">
<img width="1280" alt="radiant2" src="https://cloud.githubusercontent.com/assets/388571/17828963/fed6fc40-669e-11e6-86df-c28801c84aef.png">
<img width="1280" alt="radiant3" src="https://cloud.githubusercontent.com/assets/388571/17828965/fee48d24-669e-11e6-8993-3964129e4970.png">
<img width="1280" alt="radiant4" src="https://cloud.githubusercontent.com/assets/388571/17828964/fee21738-669e-11e6-9940-2c66169ed6d7.png">

Unfortunately changing the Safari cookie setting has had no effect here.

**Comment by jacobwgillespie** [comment]
This is an issue on Google's end, so that's good that using Safari cookies is fixing.

Closing this for now - post back if anything changes.

**Comment by gunnarbeutner** [comment]
Well, using Safari cookies does not seem to fix this for me. Also, I'm _not_ getting an HTTP error here.
