### ISSUE TITLE
App Crashes When Leaving Fullscreen Mode

### ISSUE THREAD

**Issue by dponinski** [radiant-player/radiant-player-mac#595]
When trying to exit fullscreen with custom title bar turned on the app will hang for a minute and then crash. Turning off the custom header option will fix the issue.

**Comment by jacobwgillespie** [comment]
Is this crash similar to #582 (similar error)?  This may be the same issue...

**Comment by dponinski** [comment]
That would be the one. I looked to see if someone had the same issue and I guess I over looked it. You can close this out and I'll post my comment/findings their. Thanks.
