### ISSUE TITLE
No Proxy Settings

### ISSUE THREAD

**Issue by erichlf** [radiant-player/radiant-player-mac#598]
When opening Radiant Player I get "an SSL error occurred and a secured connection to the server cannot be made." As my work requires a proxy I am guessing this is the cause. I checked the program settings and cannot find anything relating to proxy  settings.

**Comment by jacobwgillespie** [comment]
The system proxy settings on OSX in the network manager will apply to Radiant as well as all your other apps - Radiant doesn't do anything different from Safari in that regard. Are you able to access Google Play Music in Safari?

**Comment by erichlf** [comment]
Except the system proxy settings are not working for Radiant Player.

**Comment by jacobwgillespie** [comment]
Does Google Play Music work in Safari for you?  Radiant does nothing special with proxies, so you may have to adjust your system configuration to allow Radiant to use the global proxy settings.

**Comment by erichlf** [comment]
Yes, google play music works everywhere except Radiant, including Google Play Music Desktop Player. How would I change settings to allow Radiant to use the global proxy settings?

**Comment by jacobwgillespie** [comment]
You're going to have to check with your work on that one.  The proxy settings built in to OSX apply to all applications, and I just verified on my local machine that they apply to Radiant as well.  There's one of at least two things going on in your case:

* The way the proxy was configured is not standard and your work will need to do something to allow Radiant
* Your proxy is working, but it is performing a man-in-the-middle certificate replacement on Google's domain, which is causing Radiant to throw a SSL warning

Both would require your work to look at what's going on as your setup is specific to that environment.
