### ISSUE TITLE
Radiant Player Fails To Show Library 

### ISSUE THREAD

**Issue by robertsonsamuel** [radiant-player/radiant-player-mac#602]
Version 1.10.2
"CustomError: Error in protected function: Invalid listener argument" shows in the console. App only displays "Loading Music Library"

**Comment by tjanson** [comment]
Please check whether this is a duplicate of #589 (you'll find some workarounds there too).

**Comment by robertsonsamuel** [comment]
This was a duplicate of #589, the custom build 002 fixed it for me. Sorry the search wasn't very good on my part. Closing.
