### ISSUE TITLE
Navbar Thumbs Up Draw Issue

### ISSUE THREAD

**Issue by grassymeadow** [radiant-player/radiant-player-mac#605]
There appears to be an odd Thumbs Up icon in the Navbar when playing a song that has been Thumbs Up. 

OSX 10.11.6
Radiant v. 1.10.3

![media-20160915](https://cloud.githubusercontent.com/assets/18124220/18569163/9c0fe3a6-7b66-11e6-9ecc-0600fdc5b80f.png)

**Comment by jacobwgillespie** [comment]
This should be resolved by v1.11.0.
