### ISSUE TITLE
v1.10.3 introduces black color glitch 

### ISSUE THREAD

**Issue by joeljfischer** [radiant-player/radiant-player-mac#606]
As of v1.10.3 actively playing songs appear white, as if they are themed with the default theme.

**Comment by MarshallOfSound** [comment]
Ref https://github.com/gmusic-utils/gmusic-theme.js/pull/54/files

**Comment by BarakaAka1Only** [comment]
Can you give a screenshot? or the section it which that is doing that?

I'm pretty sure i fixed it as i just re-did some of the CSS and i noticed it on the song row list with 

`
.material .song-row.selected-song-row td, .material .song-row.currently-playing td
`

If that is the case, it will be fixed once a Radiant Team Member merges the changes via PR

and @MarshallOfSound thanks for the link :)

**Comment by joeljfischer** [comment]
I'm seeing it on the album screen like so: https://www.dropbox.com/s/1oe80wy45fhxecv/Screenshot%202016-09-19%2013.47.13.png?dl=0

**Comment by BarakaAka1Only** [comment]
@joeljfischer yup that's exactly what i saw and i've fixed it, will be submitting a PR soon thanks for the screenshot 👍

**Comment by jacobwgillespie** [comment]
This should be resolved by v1.11.0.
