### ISSUE TITLE
feature request: pause on screen lock

### ISSUE THREAD

**Issue by trebor** [radiant-player/radiant-player-mac#607]
add an option to pause music on screen lock.

**Comment by BarakaAka1Only** [comment]
Went ahead and took a look into this and it was pretty easy to add once i read the docs on the how-to :)

Screenshot(s):

![image](https://cloud.githubusercontent.com/assets/2947494/18604903/5b3f8d0c-7c49-11e6-922f-ea938bccd843.png)

Go to the Preferences -> General -> Check on Toggle current music play status

You can test it in REAL time without having to reload the Radiant Player App; do control + shift + eject or press Login Window :

![image](https://cloud.githubusercontent.com/assets/2947494/18605340/e72d72ec-7c54-11e6-8f59-cc0725e33519.png)

Both will trigger the music to PAUSE and PLAY if there is any item that is playing of-course

Screen Locked  = PAUSE music

Screen Unlocked  = PLAY music

and if you uncheck  Toggle current music play status you will see it off added for users that don't want to use this option Default state is off

Reference: @jacobwgillespie :)

### **Download:**

https://www.dropbox.com/s/kqzkfaq3kpl31fk/Screen%20Locked%20%3A%20Unlocked%20Radiant%20Player.zip?dl=0

Let me know if it works for you 

Tested on Yosemite and & macOS Sierra

**Comment by jacobwgillespie** [comment]
This should be resolved by v1.11.0.

**Comment by BarakaAka1Only** [comment]
@jacobwgillespie as i said in my PR this wasn't included, i can add it with another PR i didn't add because i wasn't sure if it was highly needed.

**Comment by jacobwgillespie** [comment]
Oh, oops...  :)  Yeah, feel free to PR and I'll get it merged.

**Comment by BarakaAka1Only** [comment]
Okay PR will be up in a few :)

**Comment by BarakaAka1Only** [comment]
PR submited @jacobwgillespie :D

**Comment by trebor** [comment]
wow, this is all amazing!  thank you @BarakaAka1Only!

**Comment by BarakaAka1Only** [comment]
No problem :) @trebor
