### ISSUE TITLE
macOS Sierra: Error loading library

### ISSUE THREAD

**Issue by donlion** [radiant-player/radiant-player-mac#608]
After having updated to macOS Sierra, Radiant Player can't load my library.
<img width="340" alt="screen shot 2016-09-21 at 10 14 26" src="https://cloud.githubusercontent.com/assets/2965242/18703077/aeb2ff84-7fe4-11e6-9def-dacb36d72c7b.png">

**Comment by milansamardzic** [comment]
+1 same issue

**Comment by donlion** [comment]
Might be a duplicate of #600 .. Not too sure

**Comment by xrubioj** [comment]
Enabling the use of Safari cookies mentioned in #600 fixed the issue for me. The exact comment is https://github.com/radiant-player/radiant-player-mac/issues/600#issuecomment-247295337

**Comment by noahjensen** [comment]
Yup, enabling Safari's cookies worked for me too. Thanks!

**Comment by mordocai** [comment]
Please note that while the comment @xrubioj linked to has a working download, there is a v2 of it with more fixes down below at https://github.com/radiant-player/radiant-player-mac/issues/600#issuecomment-247714939

**Comment by BarakaAka1Only** [comment]
A PR will be submitted today didn't have time the last few days but it will be PR'ed today sorry about the wait.

**Comment by BarakaAka1Only** [comment]
PR has been submitted once @jacobwgillespie or someone from the Radiant Player Team hops on and merges the changes a new version will be out :)

**Comment by xrubioj** [comment]
@mordocai You're right, I saw the big chunk of code in this comment and I missed the download link. ;)

**Comment by jacobwgillespie** [comment]
This should be resolved by v1.11.0.

**Comment by xrubioj** [comment]
Yay! It's working for me. Set the cookie store back to application internal one and works perfectly. Thanks!
