### ISSUE TITLE
Radiant says that flashplayer is missing but it is installed

### ISSUE THREAD

**Issue by ntimo** [radiant-player/radiant-player-mac#615]
Hello,

I am having the flash player installed on my macbook but the radiant player app still says that it is missing. And so I won't get any sound when playing music..

Thank for your help,
Timo

**Comment by tjanson** [comment]
How did you install Flash? Are you sure you installed the browser plugin
and not the standalone SWF player (e.g., flash-npapi in Homebrew)?

**Comment by ntimo** [comment]
I Installed the flash system plugin.

**Comment by CraigKennedy** [comment]
I had already installed the chrome plugin and the stand-alone plugin, but it didn't work until I downloaded and installed using Safari instead of Chrome.  I hope this helps...

**Comment by jacobwgillespie** [comment]
@CraigKennedy is correct, only the Safari plugin (installing Flash from inside Safari) affects Radiant - the other browsers have their own separate copy.

**Comment by Jaribeau** [comment]
This fixed the problem for me:
System Preferences > Flash Player > Updates 
Where it says

>"NPAPI Plug-in is not installed." 

Click Install Now

Thanks to mdtrice, who commented that solution [here](https://github.com/radiant-player/radiant-player-mac/issues/38#issuecomment-218960135).

**Comment by jacobwgillespie** [comment]
Going to close this as installing Flash from Safari or the solution mentioned [here](https://github.com/radiant-player/radiant-player-mac/issues/38#issuecomment-218960135) should work.  Feel free to post back if you're still experiencing issues.
