### ISSUE TITLE
Google Play Music updated web interface

### ISSUE THREAD

**Issue by mvicari** [radiant-player/radiant-player-mac#618]
Breaks interface in Radiant Player.

[See Google blog post](https://blog.google/products/google-play/introducing-the-new-google-play-music/)

**Comment by ggrell** [comment]
1.11.2 (dark theme) still works for me with the new Music UI.

**Comment by s1rd4v3** [comment]
even on the dark theme i get an error since this update by google
![2016-11-18 at 15 11](https://cloud.githubusercontent.com/assets/914248/20432872/8292824a-ada1-11e6-8d27-4b55e99ccbc4.png)

**Comment by shawn-mitch** [comment]
FWIW, the other sections are still usable and you can still listen to music. The homepage is just broken.

**Comment by shawn-mitch** [comment]
I figured it out! You just need to log out and log in again to get the new homepage to work in Radiant. The visuals need tweaking (especially if you're using one of the dark themes) but it works!
![screen shot 2016-11-26 at 12 13 25 am](https://cloud.githubusercontent.com/assets/5890308/20638430/5cc3eb90-b36d-11e6-9b11-89671731abc0.png)

**Comment by jacobwgillespie** [comment]
Closing this for now - if you're experiencing this issue, try logging out and logging back in as @shawn-mitch mentioned.

Feel free to post back if that doesn't solve.
