### ISSUE TITLE
V1.11.4 Can't Open Home Page

### ISSUE THREAD

**Issue by spc9999** [radiant-player/radiant-player-mac#634]
Was happening with 1.11.2, just upgraded, same issue. On startup, or after clicking home, the screen is blank out and a dialog states "Couldn't fetch recommendations, try again."

Screenshot:

<img width="442" alt="scs1" src="https://cloud.githubusercontent.com/assets/3051632/21373926/90568f94-c6f0-11e6-8bf7-5ee9bb896a10.png">

**Comment by jacobwgillespie** [comment]
Can you try logging out of Google Play Music and logging back in inside the Radiant app?  That fixed the issue in #621

**Comment by spc9999** [comment]
Yup that did it. Thanks!
