### ISSUE TITLE
Impossible to get suggestions on launch/home screen

### ISSUE THREAD

**Issue by rickette** [radiant-player/radiant-player-mac#635]
Hi,

It's been around 2-3 weeks now that when the app is launched i can't get a proper home screen. There's a blank screen and a dialog box saying that it is "impossible to fetch suggested content".
reloading the interface does not help, neither is changing screen or reopening the app.

Anyone have the same issue ?

**Comment by chrismou** [comment]
Looks like this is solved by logging out and back in to the app:  https://github.com/radiant-player/radiant-player-mac/issues/621#issuecomment-263046702

Let us know if you're still having problems after trying that!

**Comment by rickette** [comment]
Thank you, it worked like a charm

**Comment by chrismou** [comment]
:+1:
