### ISSUE TITLE
Home: "Couldn't fetch recommendations"

### ISSUE THREAD

**Issue by ryofurue** [radiant-player/radiant-player-mac#639]
I think this started when Google Play Music remodeled its "Home" page.  When I launch Radiant Player, an empty page is displayed with an error message "Couldn't fetch recommendations. Please try again."  When I (try to) go to the "Home" pane, the same error message is displayed and I cannot move to the home pane.

I thought this was a temporary problem; I thought that it's simply because Google changed something and that Radiant Player would catch up soon.  But, it's been quite a while like this, and I started to wonder if it was happening only to me.

If it's just that the developers are taking time, that's perfectly fine. I'm not complaining at all.  I was just wondering if this was an unreported problem.

**Comment by chrismou** [comment]
Can you try logging out of Google Play Music and logging back in inside the Radiant app?

This was reported in #621, and that seems to fix it

**Comment by ryofurue** [comment]
> Can you try logging out of Google Play Music and logging back in inside the Radiant app?

That did fix the problem. Thanks you!

> This was reported in #621, and that seems to fix it.

I wonder why the search didn't show that thread.  I thought I searched the issues for "fetch" or "home" but didn't find it.  Probably I wasn't using a correct filter.

**Comment by chrismou** [comment]
Awesome, glad it's sorted! :+1:
