### ISSUE TITLE
macOS Sierra: No library after upgrade

### ISSUE THREAD

**Issue by davidhatten** [radiant-player/radiant-player-mac#640]
Hi, just upgraded to Sierra, and Radiant Player seems to be broken. It can open and show the window frame, but there are no contents, nothing in my library, and I'm unable to search for anything. It's just blank.

This worked yesterday, before the Sierra upgrade.

**Comment by jacobwgillespie** [comment]
I'm running Sierra without any issues, so we should be able to get this figured out.  Can you right-click on the blank space, pick Inspect Element, and post back with a screenshot of the console tab?

**Comment by jacobwgillespie** [comment]
Oh, and if you're getting the "Can't load library" error, can you sign out from within Radiant and sign back in?  That fixes that particular error.

**Comment by davidhatten** [comment]
Oh, thanks, logging out and logging back in worked. I'll try to search the closed bugs too next time; didn't realize I'm 6 months behind on this update 😁

**Comment by jacobwgillespie** [comment]
Awesome, glad it's working for you!
