### ISSUE TITLE
Too many logouts

### ISSUE THREAD

**Issue by Tusko** [radiant-player/radiant-player-mac#641]
Hello! 
I'm tired enter your login and password every 20-30 minutes.

**Comment by tjanson** [comment]
This should not happen, I never need to re-login. What are your cookie settings in this window?
<img width="532" alt="screen shot 2017-01-27 at 17 27 58" src="https://cloud.githubusercontent.com/assets/532114/22378452/f39a1e9e-e4b5-11e6-813f-93708e374d22.png">

**Comment by Tusko** [comment]
@tjanson WOW! I didn't know about it section. Thank you, I'll try it :)
