### ISSUE TITLE
What's the estimated release date of 2.0?

### ISSUE THREAD

**Issue by Evertt** [radiant-player/radiant-player-mac#654]
I read somewhere that you're completely rewriting it for 2.0 in a way that doesn't require flash anymore, right? I'm eager to know when you think you'll be finished with that.

**Comment by jacobwgillespie** [comment]
Hey, honestly I haven't had really any available free time to work on this for several months now.  So I'm not really sure when an estimated release date would be...  I personally use the alpha build located here: https://github.com/radiant-player/radiant-player-electron/releases.  It has essentially no features except for keyboard control, so no themes, scrobbling, etc.  Of course if anybody wants to contribute pull requests, I would be thrilled!  Other than that, the release date would be "whenever I have time to work on it" which unfortunately I'm not able to predict.

Sorry about that!
