### ISSUE TITLE
Player asking for access to google-analyitics.com port:433 on launch

### ISSUE THREAD

**Issue by shimsy** [radiant-player/radiant-player-mac#656]
I noticed on initial start radiant-player-mac is asking for access to google-analyitics.com port:433 on launch but to my knowledge, google-analyitics.com itsn't a valid google analytics domain, in fact, following that domain in a browser redirects to a chess site.

**Comment by jacobwgillespie** [comment]
Can you verify it is actually the typo domain?  `google-analytics.com` is a valid Google domain, though `google-analyitics.com` is not.

Regardless, Radiant essentially just embeds a Safari webview, so whatever it's requesting would be the same as loading up Google Play Music inside Safari.  Anything that would modify the page in transit would be on your computer or network, not necessarily inside Radiant.

**Comment by shimsy** [comment]
Sorry about that, that was a late night typo, i'm used to seeing analytics.google.com as the standard domain used by google. So when the google-analytics.com request popped up in my firewall I thought i'd check where the dns resolves to.
Radient player was infact requesting access to google-analytics.com which is owned by google. I just accidentally put a typo in the dns search, and then copied and pasted the the same mistake into github.
Apologies for my stupidity, please close or remove this comment, and thanks for making such a great player!

**Comment by jacobwgillespie** [comment]
No worries, glad you figured it out!
