### ISSUE TITLE
Appcast not up-to-date

### ISSUE THREAD

**Issue by suschizu** [radiant-player/radiant-player-mac#681]
I think you forgot to update the changeling on https://radiant-player.github.io/radiant-player-mac/appcast/appcast2.xml - or is it intentional?

**Comment by jacobwgillespie** [comment]
Nice catch, thanks, looks like Travis CI doesn't deploy the website anymore.  I manually deployed and the latest version should appear in the XML now.

**Comment by suschizu** [comment]
thanks :)
