### ISSUE TITLE
Radiant Player crashes upon Mac OS Catalina

### ISSUE THREAD

**Issue by kostyatarasenko** [radiant-player/radiant-player-mac#682]
Radiant Player always crashes upon new Mac OS Catalina. 
No matter where it starts (from the application folder or another folder).
In settings, there aren't access check marks, because the application doesn't have time to request them.

What can I try to do?

**Comment by jacobwgillespie** [comment]
Possibly relevant: https://github.com/radiant-player/radiant-player-mac/issues/675#issuecomment-472638065

**Comment by kostyatarasenko** [comment]
> Possibly relevant: [#675 (comment)](https://github.com/radiant-player/radiant-player-mac/issues/675#issuecomment-472638065)

The application that you recommended is just the page and the shell of the site 🙁
