### ISSUE TITLE
Blocked Plug-in

### ISSUE THREAD

**Issue by philpine** [radiant-player/radiant-player-mac#69]
Since I upgraded on Mavericks, Google Music won't play any music. 
I have a "Blocked Plug-in" icon on both the title of the song and at the left of the buttons to control the music. 
![screen shot 2014-03-10 at 8 17 16 pm](https://f.cloud.github.com/assets/6913359/2380816/91aa01f0-a8b2-11e3-8b6f-8689da25e43e.png)

**Comment by eliasgomezsainz** [comment]
I've updated and reinstalled AFP, and also reinstalled Radian Player, but I can't get it to work :(

**Comment by tjanson** [comment]
@eliasgomezsainz It’s currently broken, not sure why. See the discussion in #668 – though it doesn’t contain a solution.

**Comment by chriskol** [comment]
I also have this issue now.

**Comment by Qteb** [comment]
me too
