### ISSUE TITLE
No application menu when "hide the dock icon" is enabled.

### ISSUE THREAD

**Issue by cbarrick** [radiant-player/radiant-player-mac#78]
When "Hide the dock icon when the mini player is active" is enabled, I no longer get the application menu when the window is focused; the menu of the previously focused app is shown instead. When I go to full screen, the application menu does not show up when I put the mouse at the top of the screen. This seems to be the cause of #71.

**Comment by smudge** [comment]
Control-clicking the menu icon doesn't seem to pull-up the application menu (just the mini-player still). I'm on a one-button trackpad... Do I need a mouse with a right button?
